### ISSUE TITLE
Example/Docs on how to implement firebase.storage

### ISSUE THREAD

**Issue by Bojhan** [prescottprue/react-redux-firebase#1]
There is a new helper that should allow implementation with firebase storage. I can't quite figure out how to use it to leverage existing API's, do you have a small example or docs somewhere that I can follow?

**Comment by prescottprue** [comment]
Just started the [Storage Section ](https://prescottprue.gitbooks.io/react-redux-firebase/content/storage.html) of the docs. More examples/explanation to come, but hopefully that is enough to get you started.

**Comment by towfiqi** [comment]
@prescottprue  Is there any plan on implementing [getDownloadUrl](https://firebase.google.com/docs/reference/js/firebase.storage.Reference#getDownloadURL) ? Currently after uploading the file, I have to save the url to firestore in order to show it on client. since every file automatically gets a token that should be also supplied to the url to view the image:
`https://firebasestorage.googleapis.com/v0/b/xxx.appspot.com/o/avatars%2Ftowfiqi_small.jpg?alt=media&token=4ad44cs555-ess0e5-4x8a3-83e8-xxxx3`

With firebase library there is a firebase.storage.getDownloadUrl which converts a url like `gs://xxx.appspot.com/avatars/towfiqi_small.jpg` (which is predictable) to a link like the one above.

Thanks

**Comment by prescottprue** [comment]
@towfiqi You should have access to storage on the `firebase` instance. Though nothing will be dispatched, all original methods should be preserved.

**Comment by towfiqi** [comment]
Thanks! yes. looks like it. should have [followed this doc](https://firebase.google.com/docs/storage/web/download-files#download_data_via_url).
