### ISSUE TITLE
Reads are extremely high

### ISSUE THREAD

**Issue by sbaraka** [prescottprue/react-redux-firebase#1020]
**Do you want to request a *feature* or report a *bug*?**  
bug
(If this is a *usage question*, please **do not post it here**—post it on [gitter](https://gitter.im/redux-firebase/Lobby). If this is not a “feature” or a “bug”, or the phrase “How do I...?” applies, then it's probably a usage question.)

**What is the current behavior?**
high reads when setting up as middleware. 10 document reads turn into 300 when page is only navigated to once

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

**What is the expected behavior?**

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

**Comment by prescottprue** [comment]
Could you provide a reproduction? Guessing this is for Firestore based on mention of documents? I'm not sure what you mean by "setting up as middleware" - React context is now used instead of a store enhancer or middleware.

Also would be good to clarify how you are measuring reads since to my knowledge that is done through the Firebase console

**Comment by sbaraka** [comment]
@prescottprue sorry this was an issue with my own redis cache. I am sorry I did was not more descriptive. I may have made this issue in the heat of passion! Thanks for your swiftness.
