### ISSUE TITLE
feat(auth): add support for useEmulator

### ISSUE THREAD

**Issue by benomatis** [prescottprue/react-redux-firebase#1060]
Looks like [Auth now has emulator support](https://firebase.google.com/support/release-notes/js#version_824_-_january_21_2021), would be great to see it in this package as well.

**Comment by prescottprue** [comment]
This is actually within the firebase instance instead of `react-redux-firebase`. You should be able to just use that method as you are initializing your firebase instance before passing to `react-redux-firebase`. Here is a version of the [same code in the use section of the README](https://github.com/prescottprue/react-redux-firebase#use) that includes that:


```js
// react-redux-firebase config
const rrfConfig = {
  userProfile: 'users'
  // useFirestoreForProfile: true // Firestore for Profile instead of Realtime DB
}

// Initialize firebase instance
firebase.initializeApp(fbConfig)

firebase.auth().useEmulator('http://localhost:9099/'); // enable auth emulator


// THEN LATER

const rrfProps = {
  firebase, // passing firebase instance which is already pointed to auth emulators
  config: rrfConfig,
  dispatch: store.dispatch
  // createFirestoreInstance // <- needed if using firestore
}
```

Reach out if things aren't working as you expect
