### ISSUE TITLE
Stacktrace is not source-mapped

### ISSUE THREAD

**Issue by phiiil** [prescottprue/react-redux-firebase#108]
I'm having an issue where the stack trace is not displaying the sources files and line numbers using the sourcemap. I generated a project using Yeoman. I get the same issue with the material example. Both in Chrome 56 and Firefox 47.

![image](https://cloud.githubusercontent.com/assets/1402599/24606664/31af51fe-183c-11e7-9798-53a8e705cbcd.png)

I'm using these
npm 3.8.6
node 6.10.1
webpack 1.14.0

Any ideas?

**Comment by prescottprue** [comment]
@phiiil [Created a new issue on generator-react-firebase](https://github.com/prescottprue/generator-react-firebase/issues/40) to track this since the two are separate repositories

#### Quick Thought

It is pointing you to the `NewTodoPanel` component. If you click on that, it should bring you to the that component code within the browser.
