### ISSUE TITLE
Fixed firebase version in packages.json

### ISSUE THREAD

**Issue by biomorgoth** [prescottprue/react-redux-firebase#109]
Hi,

Is there any specific reason why are we using a fixed version of Firebase (3.6.5) on this project? I would like to use a newer version of Firebase, but this does not let me.

Take a look here -> https://github.com/prescottprue/react-redux-firebase/blame/master/package.json#L53

**Comment by prescottprue** [comment]
@biomorgoth The reason that the Firebase version is locked is due to the fact that updates may change the API. Since you are hoping for this updated version though, I can see about adding the `^` to the Firebase dependency in future versions.

What version are you using currently? If you update to one of the `v1.4.0-*` versions, you will have the newer version of the Firebase library.

**Comment by biomorgoth** [comment]
I am currently using version 1.3.4 (the last non alpha nor beta version). I will test one of those versions and send some updates here on the following days.

Thanks!

**Comment by prescottprue** [comment]
[`v1.4.0-rc.1`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.4.0-rc.1) also has ^ on Firebase.

Going to leave this issue open until `v1.4.0` (non-prerelease) is released.

**Comment by prescottprue** [comment]
[`v1.4.0` was released](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.4.0) with this included, so this is now out of pre-release.
