### ISSUE TITLE
feat(example): pagination

### ISSUE THREAD

**Issue by kmsheng** [prescottprue/react-redux-firebase#111]
I want to implement pagination, a little example about this would be appreciated.

**Comment by prescottprue** [comment]
@kmsheng Will look into making one. You should be able to do it with `startAt` and `limitTo`, but will leave this open until I make the example.

**Comment by prescottprue** [comment]
Started a pagination example [on the pagination branch](https://github.com/prescottprue/react-redux-firebase/blob/pagination/examples/complete/pagination/src/Page.js#L17-L42)

It has one major flaw currently: If you go directly to a specific page (instead of using the next button to get to it), it will start on that page number (showing the first list on that page, then incrementing up from there). This is due to how firebase does queries for pagination (startAt requires a value from the last item in the previous page's query).

Starting to design a way around this by making a function that loads all previous pages in order, but that will have to be released in a future version.

**Comment by kmsheng** [comment]
Yeah, I realized that problem when I read the doc of firebase.
Thanks for providing pagination branch, maybe I will try firebase next time if the project is simpler without numeric pagination. 

Loading all previous pages is not my desired solution because it eats too much memory.

**Comment by pzmudzinski** [comment]
I am working on something similar, but my case is infinite scrolling.
So there's list of messages and when user reaches the top then next page is loaded (the same Messenger is doing). 

I am going to use mix of `orderByKey#endAt=...&limitToLast=pageSize`. 

So when you load it for first time you do 
`orderByKey#limitToLast=pageSize`.
You need to save your load-more state in some separate object (e.g. redux store). 
`pages: [ {isLoaded: true, firstElementKey: ... ]`

Then when you want to load next page (I am using [this](https://github.com/CassetteRocks/react-infinite-scroller) for scroll & load more) you do something like that:
`orderByKey#limitToLast=(pageSize+1)&endAt=pages[0].firstElementKey`.
You have one extra element so you need it to remove before rendering. 
so your state becomes:
`pages: [{isLoaded: true, firstElementKey}, {isLoaded: true, firstElementKey}]`

Next calls are the same but you just bump up page number. 
I also keep number of messages as a separate property in database so I know if there's more element to load. 

I might create some example if it's needed (and I complete it, since I don't know if that approach is correct :P ).

**Comment by prescottprue** [comment]
Not sure if it will be helpful, but here is some logic we have used:
```js
/* eslint-disable consistent-return */
const admin = require('firebase')

import { last, dropRight } from 'lodash';

try {
  admin.initializeApp(functions.config().firebase);
} catch (e) {
  console.log('Caught error initializing app with functions.config(), assuming dev environment.');
  const config = require('../functions/config'); // eslint-disable-line
  admin.initializeApp({
    serviceAccount: './serviceAccount.json',
    databaseURL: config.firebaseConf.databaseURL,
  });
}

/**
 * Paginate a path on Firebase. Promise.all is used to write current page info and start next query in parallel
 * @param  {String} path Firebase path to paginate
 * @param  {Number} [itemsPerPage=10] Number of items to place in each page
 * @param  {String} startAtKey - Key to start query at (not required for first page)
 * @param  {Number} [currentPage=0] Current page which is being paginated
 * @return {Promise}
 */
const paginate = (path, itemsPerPage = 10, startAtKey, currentPage = 0) => {
  const queryLength = itemsPerPage + 1;
  let query = admin.database().ref(path)
    .orderByKey()
    .limitToFirst(queryLength);

  // start from cursor of last query if it exists
  if (startAtKey) {
    query = query.startAt(startAtKey);
  }

  return query
    .once('value')
    .then((snap) => {
      const list = [];
      snap.forEach((childSnap) => {
        list.push(childSnap.key);
      });
      const nextStartAt = last(list);
      const isLast = list.length < queryLength;
      const promises = [
        admin.database()
          .ref('paginate/results/new')
          .update({
            [currentPage]: {
              list: isLast ? list : dropRight(list),
              nextStartAt,
            },
          }),
      ];
      // add promise to continue process if not last page
      if (!isLast) {
        promises.push(
          paginate(path, itemsPerPage, nextStartAt, currentPage + 1)
        );
      }
      return Promise.all(promises);
    });
};

const pageLength = 10;
paginate('requests/paginate', pageLength);
```

**Comment by prescottprue** [comment]
Firestore is now the preferred method for doing pagination. With that and the previously provided example in mind, going to close.

**Comment by awadesmoline** [comment]
@prescottprue I couldn't get to the example on the pagination branch link you shared above. 
@pzmudzinski were you able to create the example?
