### ISSUE TITLE
feat(auth): config option for keeping data within redux when logging out

### ISSUE THREAD

**Issue by prescottprue** [prescottprue/react-redux-firebase#125]
**Do you want to request a *feature* or report a *bug*?**  
feature

**What is the current behavior?**
Every time a user logs out, all data is removed from redux

**What is the expected behavior?**
Providing the following config will preserve a list of todos when logging out:

**NOTE** Actual API may be different:

```
reactReduxFirebase(
fbConfig,
{
  preserveOnLogout: ['todos']
}
)

```

**Comment by TheGhoul21** [comment]
what about resources that have been loaded and are linked somehow to the status of the user? 
let's say you have a list of resources visible from an anon user. BAM! loaded.  They're in the store. Then, you login, and BAM more resources are loaded, because you have visibility on them. Then you signout, You should restore the status of the store to a pre-login state I guess. And should the status be specific about the resource paths? 
I should make an example maybe:

1. on page load you see a list of free courses ( courses: dataToJs('courses') let's say)
2. after you sign-in you see the previous list of courses, with more due to the fact you're signed-in
3. you logout: you should be able to see the state you were in BEFORE signin in

This should be the correct approach IMHO, what do you think?

**Comment by prescottprue** [comment]
@TheGhoul21 That is the plan with the above mentioned API. In your case, you would preserve the list of data that was loaded as an anonymous user.

Even if you queries are at the same path, with different results if you are logged in or out, you could use `storeAs`, to keep that data in a different place in redux. Then you use the place that you have stored the query done when anonymous in your `preserveOnLogout`.

**Comment by prescottprue** [comment]
[`v2.0.0-beta`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.0.0-beta) was released and it includes this feature.

More documentation will be coming soon.

**Comment by prescottprue** [comment]
[`v2.0.0-beta.12`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.0.0-beta.12) added support for passing an object to preserve other parts of state.
