### ISSUE TITLE
Suggestion: don't `npm publish` pre-releases

### ISSUE THREAD

**Issue by Satyam** [prescottprue/react-redux-firebase#155]
May I suggest publishing to NPM only full versions, not alphas nor betas?  A plain `npm install` will install by default the latest, whichever its state might be.  

For those brave enough, they can install from a git repository.  For the rest of us, a plain `npm i` should only bring a stable, production version, no pre-releases.  

I was forced to explicitly state `npm i react-redux-firebase@1.4.0` because otherwise I got a version that did not build correctly.  The nature of the build error is irrelevant since, being a beta, it just might happen.  
What should not happen is to get unstable releases by default. Not in a module that is above semver `0.x.x`.

Thanks

**Comment by prescottprue** [comment]
@Satyam I agree that not getting unstable versions by default is expected behavior.

It seems that as of npm `v3.4.1` [this behavior changed](https://medium.com/@mbostock/prereleases-and-npm-e778fc5e2420).

Planning on starting to use the "next" tags so that this shouldn't be an issue moving forward.

Just out of curiosity, which pre-release version were you using that had a "build error"?

**Comment by Satyam** [comment]
It was whatever was `@latest` last Thursday, I think `1.5.0-beta.3`.   `babel-core` generated an error saying that it could not set a property in `undefined`, where the property was some auto-generated key, like a UUID that came out different on every try.   The error gave no clue as to what part was Babel processing at the time. Reinstalling it made no difference.  Then, I became suspect of the *beta* version and installed `@1.4.0` and it worked nicely.  However, I cannot freely update my dependencies as npm will pick the *beta* version again. 
node version: 6.11.0
npm version: 5.0.3
Ubuntu 16.04 LTS

**Comment by prescottprue** [comment]
@Satyam This is great to know. I am interested in whether it would happen with `beta.2` and `beta.1` as well. It seems like it is one of the changes that was done for 

As for updating, in your package file can you just point to `1.4.0` instead of using `^1.4.0` or whatever is allowing you to get the `1.5.0` version?

**Comment by prescottprue** [comment]
@Satyam [`v1.4.1` is now the most recent release](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.4.1) and will install as `@latest`.

Pre-releases will now be published using tags (i.e. `npm publish --tag next` or similar) so that `@latest` (installed by default when running `npm install`) will always be only stable versions.
