### ISSUE TITLE
Set Firebase as peer dependency?

### ISSUE THREAD

**Issue by ngryman** [prescottprue/react-redux-firebase#173]
It would be nice not to enforce `firebase` as a hard dependency.

**Comment by prescottprue** [comment]
@ngryman Only as of `v2.0.0` will Firebase not be a "hard" dependency since it will allow for the passing of a Firebase instance. The weird issue about moving it to a peer dependency is that if you are hoping to not pass in a Firebase instance, you will see a complaint about not having Firebase (a peer depedency) installed.

This might mean that `v2.0.0` can only accept already initialized Firebase instances instead of allowing for config to be passed. My major hesitation there adding another requirement to the migration guide from v1 to v2 (since many users prefer that the instance is initialized internally).

In other versions Firebase is an actual dependency since it is initialized internally.

**Comment by ngryman** [comment]
Thanks for the answer.

To give you more context, my main issue is that it messes up hard with my bundler (Rollup).

What about supporting both ways by passing the `firebase` singleton like so:

1. Initialized externally: `reactReduxFirebase(firebase)` 
2. Initialized internally: `reactReduxFirebase(firebase, firebaseConfig, config)`

The migration would only require one additional leading parameter for both use cases. I think it's perfectly OK considering the benefits.

**Comment by prescottprue** [comment]
@ngryman The syntax that you listed is similar to how it is happening in `v2.0.0` (more below).

#### v1.5.*
Making Firebase an external in the `react-redux-firebase` webpack config should also solve your use case, and I will look into adding this to the roadmap (it may be a breaking change for some)

#### v2.0.*
The plan for `v2.0.0-beta` is to move Firebase to `peer-dependencies` and make it an external in webpack config

#### Side note
The future plan is to move to Rollup for building `react-redux-firebase` as well, but not yet sure if it will make it into `v2.0.0`

**Comment by ngryman** [comment]
Thanks. So if I understand well, for now I have to fork 1.x, make `firebase` as external and depend on it?

**Comment by prescottprue** [comment]
@ngryman `v2.0.0-alpha.3` was release with Firebase as a webpack external.

Planning on doing a release with a similar for 1.x this week. I am always open to pull request if you are pressed for time.

**Comment by ngryman** [comment]
@prescottprue Thanks!
