### ISSUE TITLE
Why movement away from ImmutableJS?

### ISSUE THREAD

**Issue by ksnyde** [prescottprue/react-redux-firebase#195]
I am building an Ember-redux addon and am using ImmutableJS but noticed that you are moving away from it. Can you help me understand the reason? Would love to gain from you knowledge.

**Comment by prescottprue** [comment]
There are a few reasons for the migration away from Immutable:

1. It required users of `react-redux-firebase` to convert the Immutable Map back into a JS object using `pathToJS` and `dataToJS` (instead of just getting the JS object from state directly, which is how v2.0.0 works)
1. Map objects seem to not work well with how React decides to re-rendering components (originally posted [in this issue](https://github.com/prescottprue/react-redux-firebase/issues/84), also [mentioned in this react-router-redux issue](https://github.com/reactjs/react-router-redux/issues/421))
1. It is a fairly large dependency for how little is being used from it (many users of `react-redux-firebase` want the smallest possible bundle size)
1. Using `combineReducers` as described in the redux docs simplifies reducer logic to the point of making immutable overkill (updates can be done with `set` from lodash along with spread so as to not modify existing state)
1. There was an issue where setting child data after setting a parent to null (would throw `invalid keyPath` error). This means [extra code is needed](https://github.com/prescottprue/react-redux-firebase/blob/master/src/reducer.js#L69-L73) to clear the parent
1. `fromJS` and `toJS` functions from Immutable, which are used in `pathToJS` and `dataToJS` and in reducers, can be "expensive" with respect to resources depending on the size of the data (noted by others)

There might be even more I can't think of currently, but these reasons were more than enough to warrant the removal.

If you have any more questions surrounding this, feel free to reach out over [gitter](https://gitter.im/redux-firebase/Lobby) (similar chats often go on there).

**Comment by ksnyde** [comment]
Thanks Scott. Very useful to know. I was assuming that ImmutableJS's collision detection for the state tree would pay dividends (and to be fair I was just interested in using Immutable) but I was concerned about toJS() costs. You make some good points here though and of course bundle size is always a consideration for folks.

**Comment by ksnyde** [comment]
I do have one quick question ... the way I've built my "connect" equivalent I am using Immutable's fast collision detection method of `hashCode`. Only if there is a change do I set state locally. Did you consider that approach before deciding to move away?

**Comment by prescottprue** [comment]
@ksnyde I did start to look into that option. When researching, I found [posts such as this one](https://egghead.io/lessons/javascript-lightning-fast-immutable-js-equality-checks-with-hash-codes) and tutorials [like this one](https://egghead.io/forums/lesson-discussion/topics/lightning-fast-immutable-js-equality-checks-with-hash-codes) mentioning that there is still a chance of collision.

Between having to add code for checking and the chance that there may be collision, it seemed like removing it was still the best option.
