### ISSUE TITLE
feat(integration): firebase-admin integration

### ISSUE THREAD

**Issue by kazupooot** [prescottprue/react-redux-firebase#22]
https://firebase.google.com/docs/auth/admin/manage-users

**Comment by prescottprue** [comment]
It is not currently supported, but I will add this to the roadmap.

Thanks for the suggestion!

**Comment by prescottprue** [comment]
Do you have ideas for how you would like to interact with the API?

Maybe something like this:

```js
this.props.firebase.admin().getUser()
this.props.firebase.admin().createUser()
```

Also, it will most likely require passing in an instance of `firebase-admin` that has already been initialized so that it does not have to be a dependency like so:

```js
import * as admin from 'firebase-admin'
const serviceAccount = require("path/to/serviceAccountKey.json");

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "https://<DATABASE_NAME>.firebaseio.com"
});

// Firebase config
const fbConfig = {
 apiKey: '<your-api-key>',
 authDomain: '<your-auth-domain>',
 databaseURL: '<your-database-url>',
 storageBucket: '<your-storage-bucket>'
}

// React Redux Firebase Config
const config = {
  userProfile: 'users',
  admin // pass instance of admin as admin parameter
}

// Add react-redux-firebase to compose
const createStoreWithFirebase = compose(
 reactReduxFirebase(fbConfig, config),
)(createStore)

```
I think most use cases do not involve usage of `firebase-admin` so keeping from adding it as a dependency would be ideal (hence passing of the initialized instance).

**Comment by kazupooot** [comment]
Api looks great. 👍

**Comment by kazupooot** [comment]
`I think most use cases do not involve usage of firebase-admin`

I agree.

**Comment by kazupooot** [comment]
> I think most use cases do not involve usage of firebase-admin
I agree.

**Comment by prescottprue** [comment]
This should work on v2. Just a note though: `firebase-admin` can not be used without the nodejs environment including modules like `fs`. That means it will most likely not work in front end applications without some config changes and IS NOT SUGGESTED (since service account has to be exposed).

Going to close since it is now supported.
