### ISSUE TITLE
populate by key, not value?

### ISSUE THREAD

**Issue by Talor-A** [prescottprue/react-redux-firebase#220]
In my firebase setup I have a `/users` object with this structure:
![screenshot](https://user-images.githubusercontent.com/11509865/28999627-5cf62482-7a02-11e7-89d3-6bdc31cdb8b1.png)

the IDs listed in the `groups` field correspond to other objects stored in `/groups`. I am using this snippet to populate the groups of the currently logged in user:
```
const store = createStore(
      ...
      reactReduxFirebase(firebase, {
        userProfile: 'users',
        profileParamsToPopulate: ['groups:groups'],
        enableRedirectHandling: false
      }),
```
which should populate to:

```
profile { groups { $groupID { ...groupData } } }
```

but nothing happens. 
I'm using `react-native-firebase` with `react-redux-firebase@2.0.0-beta.3`

**Comment by Talor-A** [comment]
Update: I guess this is a duplicate of #24 but it doesn't work for me :cry:

**Comment by prescottprue** [comment]
@Talor-A Not really understanding what you are going for here.

Your first example would not work because `v2.0.0` requires usage of `populate` along with `propfileParamsToPopulate` to get populated profile data (this is mentioned in [the migration guide](http://docs.react-redux-firebase.com/history/v2.0.0/docs/v2-migration-guide.html#what-changed), but it should be improved to be more clear). There has also been discussion of providing a `autoPopulateProfile` config option for v2.

For now though you would need something like this:

```js
export const populateSettings = [{ child: 'groups', root: 'groups' }]

const store = createStore(
      ...
  reactReduxFirebase(firebase, {
    userProfile: 'users',
    profileParamsToPopulate: populateSettings,
    enableRedirectHandling: false
  }),
)

// then later in you component
@connect(({ firebase }) => ({
  profile: populate(firebase, 'profile', populateSetings) // populate settings are 
}))
```


The example you provide in your second comment does not seem to be using the same population parameters (likes instead of groups), but does look to be correct. Since it is not function as expected, I will try to reproduce the issue myself.

**Comment by Talor-A** [comment]
Thanks, did not realize the profile has to be populated. I'll test it again

**Comment by amaldare93** [comment]
Im having the same issue; am I doing this right?

Firebase Data
```js
{
  "users": {
    "1zZtlyXledeYbQuxxmXjgLIoC8i1": {
      "uid": "1zZtlyXledeYbQuxxmXjgLIoC8i1"
    },
    "460484He59SlOSwSHUzfyf8XtBy2": {
      "uid": "460484He59SlOSwSHUzfyf8XtBy2"
    },
    "Tsh8gMlNSDUhy8DzRG2eni3RdeE2": {
      "uid": "Tsh8gMlNSDUhy8DzRG2eni3RdeE2"
    },
    "UP2Ass6ZrgcUCzoYyV8IrhToFTC3": {
      "nearbyUsers": {
        "1zZtlyXledeYbQuxxmXjgLIoC8i1": true,
        "460484He59SlOSwSHUzfyf8XtBy2": true,
        "Tsh8gMlNSDUhy8DzRG2eni3RdeE2": true,
        "xiALqEghGUTui16MuS1MkS7dCvT2": true
      },
      "uid": "UP2Ass6ZrgcUCzoYyV8IrhToFTC3"
    },
    "xiALqEghGUTui16MuS1MkS7dCvT2": {
      "uid": "xiALqEghGUTui16MuS1MkS7dCvT2"
    }
  }
}
```


```js
const reactReduxFirebaseConfig = {
  userProfile: 'users',
  profileParamsToPopulate: [{ child: 'nearbyUsers', root: 'users' }],
}
```

```js
@connect(({ firebase }, { currentUserId }) => {
  return {
    profile: populate(firebase, 'profile', [{ child: 'nearbyUsers', root: 'users' }]),
  }
})
```

Resulting profile prop:
```js
{
  uid: "UP2Ass6ZrgcUCzoYyV8IrhToFTC3",
  nearbyUsers: {
    1zZtlyXledeYbQuxxmXjgLIoC8i1: true,
    460484He59SlOSwSHUzfyf8XtBy2: true,
    Tsh8gMlNSDUhy8DzRG2eni3RdeE2: true,
    xiALqEghGUTui16MuS1MkS7dCvT2: true
  }
}
```

**Comment by prescottprue** [comment]
@amaldare93 Populating multiple things with users will may cause you an issue with how things work currently. Going to try a similar pattern in the material example to confirm.

The feature mentioned in #126 would allow you to store the results of the different populate queries under different keys in redux, but I would rather address your issue (since your example looks correct at first glance).

**Comment by amaldare93** [comment]
thanks, i appreciate you looking into these issues 👍

**Comment by prescottprue** [comment]
@amaldare93 [The recent release of `v2.0.0-beta.8`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.0.0-beta.8) includes smarting merging and improved population logic.

Other than that I am not able to reproduce.

**Comment by amaldare93** [comment]
i think i got around that original problem by upgrading to beta.5 and  populating everything via `profileParamsToPopulate`. 

Are there any differences (performance, functional, real time updating) between populating values through the profile vs with `firebaseConnect` ?
