### ISSUE TITLE
[v2] Getting `TypeError: firebase.auth is not a function` when passing a Firebase app instance

### ISSUE THREAD

**Issue by nicolasgarnier** [prescottprue/react-redux-firebase#249]
I'm getting the following error when passing a firebase App instance rather than the firebase library to `reactReduxFirebase` :

```
TypeError: firebase.auth is not a function
    at Object.init (/Users/nivco/Documents/workspace/friendlypix-web-react/node_modules/react-redux-firebase/lib/actions/auth.js:162:12)
```

Here is how to reproduce the issue:

```js
import firebase from 'firebase';

const firebaseApp = firebase.initializeApp(fbconfig);

// ...

export const store = createStore(
  combineReducers({
    ...reducers,
    firebase: firebaseStateReducer
  }),
  compose(
    applyMiddleware(thunk.withExtraArgument(getFirebase)),
    reactReduxFirebase(firebaseApp)
  )
);
```

This code, however, works (where I pass the firebase lib rather than a Firebase App instance):

```js
import firebase from 'firebase';

const firebaseApp = firebase.initializeApp(fbconfig);

// ...

export const store = createStore(
  combineReducers({
    ...reducers,
    firebase: firebaseStateReducer
  }),
  compose(
    applyMiddleware(thunk.withExtraArgument(getFirebase)),
    reactReduxFirebase(firebase)
  )
);
```

However the best practice should be to pass a firebase App instance rather than the firebase library. The app Instance (`firebaseApp` in the code) should work similarly, it definitely has an `auth()` function so I'm not sure why we're getting this error.

**Comment by prescottprue** [comment]
@nicolasgarnier Which version are you using? This syntax only works with v2. [Here are the docs about the migration from v1 -> v2](http://docs.react-redux-firebase.com/history/v2.0.0/docs/v2-migration-guide.html#pass-in-firebase-instance).

**Comment by prescottprue** [comment]
Ahh... Just noticed the v2 in the title. Attempting to replicate now. 

The initial thought was to pass the whole library since there could be multiple app instances, but I agree it would be best to pass the instance. It seems like it would make it easier to run firebase apps side by side in the same store (currently when doing this users have stored other apps under different store keys).

**Comment by prescottprue** [comment]
As I mentioned in #250, [`v2.0.0-beta.7`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.0.0-beta.7) includes support for passing just the app instance.

**Comment by nicolasgarnier** [comment]
Sweet! Thanks so much @prescottprue

**Comment by nicolasgarnier** [comment]
works like a charm! 👍

**Comment by wizzywit** [comment]
hello i am having a slight issue on my react app concerning this same typeError: firebase.auth not a funtion but am not passing a firebase app instance

the code below is my index.js
![snnipet 1](https://user-images.githubusercontent.com/40175713/54845571-f693b400-4cd9-11e9-92f9-14cceedcb15f.PNG)

 below is my fbConfig.js file
![fbConfig](https://user-images.githubusercontent.com/40175713/54845598-11febf00-4cda-11e9-9888-c79c2a7b5237.PNG)

also the authAction.js file
![authAction](https://user-images.githubusercontent.com/40175713/54845615-2642bc00-4cda-11e9-90b3-f6291ef05df7.PNG)

So finally this is my Signin.js which contains the higer order component connect to mapDispatchToProps
![signin1](https://user-images.githubusercontent.com/40175713/54845739-7a4da080-4cda-11e9-8c78-31470a11e02c.PNG)
![signin2](https://user-images.githubusercontent.com/40175713/54845746-7e79be00-4cda-11e9-929f-8091f8249acf.PNG)
 please i would require your assistance in this regards thanks

**Comment by wizzywit** [comment]
below is the error message i get
![error](https://user-images.githubusercontent.com/40175713/54845838-bb45b500-4cda-11e9-97c5-a4830bb61c4f.PNG)

**Comment by prescottprue** [comment]
@wizzywit As per the setup examples you should be calling `initializeApp` in when creating the store instead of in the config file. Try exporting just the config from your fbConfig file instead of the whole firebase instance - it seems like some of the firebase lib is not being passed on.

**Comment by wizzywit** [comment]
okay thanks.. did what you suggested still giving same error

**Comment by prescottprue** [comment]
`getFirebase` is a function that returns the internal Firebase instance - it does not return the instance itself. You should change the following:

```js
// const firebase = getFirebase // DO NOT DO THIS

const firebase = getFirebase() // make sure you invoke getFirebase
```

All of this noted: you shouldn't need to be creating a seperate action with dispatches since actions are dispatched when you call [`login`](http://react-redux-firebase.com/docs/auth.html#logincredentials). Also worth noting: the plan is to remove `getFirebase` in coming version (as mentioned [in the migration guide](http://docs.react-redux-firebase.com/history/v3.0.0/docs/v3-migration-guide.html)) due to the usage of the new context API (instead of storing the instance on `store.firebase`)
