### ISSUE TITLE
bug(populate) not working when firebaseConnect multiple paths

### ISSUE THREAD

**Issue by ucare-wuh** [prescottprue/react-redux-firebase#259]
**Do you want to request a *feature* or report a *bug*?**  
bug

**What is the current behavior?**
populate is not working when multiple paths specified in @firebaseConnect.

```js
// The following code results in undefined 'members'
@firebaseConnect([{
  path: `/messages/group1`
}, {
  path: `/members/group1`,
  populates: [{ child: 'user', root: 'users' }]
}])
@connect(({ firebase }) => {
  const populated = populate(firebase, `/members/group1`, [{ child: 'user', root: 'users' }])
  // populated = undefined   <- wrong
})

// But it works correctly with a single path in firebaseConnect
@firebaseConnect([{
  path: `/members/group1`,
  populates: [{ child: 'user', root: 'users' }]
}])
@connect(({ firebase }) => {
  const populated = populate(firebase, `/members/group1`, [{ child: 'user', root: 'users' }])
  // populated = { ... }   <- correct
})
```

**What is the expected behavior?**
It should populate correctly.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
Found this issue on 2.0.0-beta.7.

**Comment by prescottprue** [comment]
@ucare-wuh What is the intention with multiple queries to the same path without different `queryParams` in your first example?

As things are currently, multiple queries to the same path with the same query parameters (what your first example does) only sets the first query. This is intentional to match Firebase's internal logic that does not set another listener to a query path if one already exists.

That means that in your first example, the query with populates is not ever getting set, which would mean that the associated populate queries are also never set. The data for `members/group1` is still loaded, but `populate` will return `undefined` since the data for population is not available.

**Comment by ucare-wuh** [comment]
@prescottprue , they are not the same path. The first one is 'messages' the second one is 'members'. 'group1' is the group id.

messages and members can be successfully loaded into data without any population.

If I understand this mistakenly, please kindly let me know too.

**Comment by ucare-wuh** [comment]
@prescottprue , I found the issue was on my side. My program did not handle the case where populated value is `undefined` before promise resolves. An error was raised and stoped the process, leading the populated value did not get set in store.

Sorry for the trouble and thank you very much!
