### ISSUE TITLE
SET action is called multiple times

### ISSUE THREAD

**Issue by Morphexe** [prescottprue/react-redux-firebase#27]
I am trying your library as away to facilitate the bindings, but I am currently hitting a dead end.
The Set Action is being constantly called, is this the expected behaviour?

this is what I am using to connect the library and redux.
````

const fbWrappedComponent = firebaseConnect(
    ({ profile }) => ([
        `/messages/${profile ? profile.uid : 'noUser'}/notifications`
    ])
)(UserLayout)



const authWrappedComponent = connect(
    ({ firebase }) => ({
        profile: pathToJS(firebase, 'profile')
    })
)(fbWrappedComponent)


export default connect(
       
    ({ firebase }) => ({
        authError: pathToJS(firebase, 'authError'),
        auth: pathToJS(firebase, 'auth'),
        profile: pathToJS(firebase, 'profile'),
        messagesNotifications: dataToJS(firebase, `/messages/${firebase.profile ? firebase.profile.uid : 'noUser'}/notifications`)
    },
        (dispatch) => ({
            pushRoute(r) { dispatch(push(r)) }
        })
    )
)(authWrappedComponent);`


```

Did I messed up somewhere? The way I see it the Set Action should be only called when the data changes right? 
There are no changes happening at all currrently.

**Comment by prescottprue** [comment]
If you are having constant calls happen it is usually due to multiple of the same prop being passed in multiple connect calls (as props update, connect will be called over and over). Not positive but it might be due to setting `profile` multiple times. Below are some patterns that may help

### Patterns
* Avoid passing props you are not using (keeps component from updating unnecessarily)
* Avoid passing props of the same name (passing `profile` or `auth` multiple times)
* When using user's UID, I would use `auth.uid`
* Not sure that you are using the second argument of `connect` correctly (I could be wrong). From what I have seen, one usually passes an object with parameters associated to the prop that action is being set to within the component like so:

  ```js
  {
    someAction: (dispatch) => ({
        pushRoute(r) { dispatch(push(r)) }
    })
  }
  ```

### What You Want
I believe what you are looking for is something similar to the following:

```js
// Get Auth from redux state and pass as prop
const authWrappedComponent = connect(
  ({ firebase }) => ({
      auth: pathToJS(firebase, 'auth')
  })
)(UserLayout)

// Load /messages/${auth.uid}/notifications into redux
const fbWrappedComponent = firebaseConnect(
  ({ auth }) => ([
    `/messages/${auth ? auth.uid : 'noUser'}/notifications`
  ])
)(UserLayout)

// Place /messages/${auth.uid}/notifications from redux state into notifications prop
export default connect(
  ({ firebase, auth }) => ({
    notifications: dataToJS(firebase, `/messages/${auth ? auth.uid : 'noUser'}/notifications`)
  }),
  {
    // this.props.goToNewRoute will now be this thunk action
    goToNewRoute: (dispatch) => ({
      pushRoute(r) { dispatch(push(r)) }
    })
  }
)(fbWrappedComponent);
```

I may be able to be a little bit more helpful if you provide a repo/codepen that replicates your error, but hopefully that helps. Going to leave the issue open until we confirm it is not due to an error in the library.

Thanks for reaching out! Feel free to reach out over [gitter](https://gitter.im/redux-firebase/Lobby) if you need quicker responses or just want to chat.
