### ISSUE TITLE
Firestore integration?

### ISSUE THREAD

**Issue by benoj** [prescottprue/react-redux-firebase#284]
Just seen this has been released: https://firebase.google.com/docs/firestore

Is this worth including into this library?

**Comment by D1no** [comment]
For people who are confused what the difference is to the firebase real-time database, here is a blog post: https://firebase.googleblog.com/2017/10/cloud-firestore-for-rtdb-developers.html

Fair to expect, that Firestore will be somewhat the successor

**Comment by benoj** [comment]
@D1no yeah seems that way, although it is still in beta - possibly worth a fork or feature switch?

**Comment by prescottprue** [comment]
I have created a new library called [`redux-firestore`](https://github.com/prescottprue/redux-firestore) that will house logic for redux + firestore (research has been going on for a few months while the product was still in alpha).

It is intentionally front-end framework agnostic so that it can eventually be used in a framework specific library similar to `react-redux-firebase` (or even just used in here).

This was done to match the plan for moving the framework agnostic core of this library to `redux-firebase`. Then, way in the future, if things are similar enough, then `redux-firebase` may potentially also require/use `redux-firestore` so that one top level library can be used regardless of whether you are using realtime database of Firestore.

**Comment by drailanjohngss** [comment]
can It be integrated with expo?
