### ISSUE TITLE
feat(core): support for Cloud Firestore

### ISSUE THREAD

**Issue by sh-a-v** [prescottprue/react-redux-firebase#286]
What about [Cloud Firestore](https://firebase.google.com/products/firestore/)?

**Comment by max-barry** [comment]
Looks like the maintainer is [also working on Firestore bindings](https://github.com/prescottprue/redux-firestore).

That project currently doesn't build (from NPM or direct from the Git), but this is all great work so happy to be patient!

**Comment by prescottprue** [comment]
@sh-a-v Yup, @max-barry is correct about the separate Firestore bindings. 

[As mentioned in this issue](https://github.com/prescottprue/react-redux-firebase/issues/284) there is a [separate gitter channel just for the Firestore](https://gitter.im/redux-firestore/Lobby) stuff. That being said there is also a longer term plan of making them both available from a library like `react-redux-firebase`.

@max-barry You are right about it not being at all complete or even building. Over the next few days I am working on copying a bunch of work I had done during the Alpha testing (last few months) to the publish package (it all had to be private before).

**Comment by prescottprue** [comment]
Things are getting close with `redux-firestore`.

I can now confirm that `react-redux-firebase` will soon have Firestore capabilities. Logic is being strategically separated in to libraries so that only what is needed can be imported while still providing everything to libraries like `react-redux-firebase`.

Separating things may seem like overkill, but it is an intentional pattern. There are many, but one main benefit is that non-react libraries/projects can also still make use of all of the redux logic.

**Comment by prescottprue** [comment]
`redux-firebase` is now passing the unit tests from `v2.0.0` of `react-redux-firebase`, so now it is just a matter of wiring it into `react-redux-firebase` which is planned for the next few days.

There are not yet tests or docs for the Firestore stuff, so that and a `firestoreConnect` or similar are still to come.

Thanks to everyone for the patience and help with testing while things are being built out. My company is currently starting the move over to `react-redux-firebase` `v2.0.0` from `v1.*.*` and it has been keeping me super busy.

**Comment by Modestas** [comment]
Just for clarification, correct me if I'm wrong:

- I'm using `react-redux-firebase v2` and `Firebase Realtime Database`
- `redux-firebase`, `redux-firestore` and `react-redux-firebase` are finished for integrating.
- I switch my database from `Realtime Database` -> `Cloud Firestore` and change in my code that `react-redux-firebase` will use `redux-firestore` instead of `readux-firebase`.
- compatibility code changes are **NOT** required

**Comment by prescottprue** [comment]
@Modestas To clarify:

* **Yes** - keep using `react-redux-firebase v2` and `Firebase Realtime Database`. `redux-firestore` and `redux-firebase` are lower level libraries that will be used in `react-redux-firebase v2`
* **Kinda** - Yes they are for the most part "finished for integrating" **BUT** are not actually integrated yet (which is what I am working on today). I would *suggest not using* `redux-firebase` or `redux-firestore` yet unless you are intending to actively help build/debug the library (it would be good to reach out over [gitter](https://gitter.im/redux-firestore/Lobby) to make sure we are all on the same page).
* **Yes** - `react-redux-firebase` will make use of both internally and point to `redux-firebase`
* **Yes** - Code changes will not be required if you are already using `react-redux-firebase` v2

The intention was to have all of the complete before it was really noticeable so it isn't so unclear, but the only real change that users of `react-redux-firebase` should see is more features (i.e. firestore capabilities).

**Comment by prescottprue** [comment]
### Update

The first phases of integration of `redux-firestore` into `react-redux-firebase` are on the [`v2.0.0-beta.11` branch](https://github.com/prescottprue/react-redux-firebase/pull/295).

`firestoreConnect` was added and `firestoreReducer` from `redux-firestore` is exposed so it can be used along side your current firebase reducer.

There is still a bit of work to do with correctly tracking listeners in certain situations, so it isn't ready to release yet.

**Comment by prescottprue** [comment]
[`v2.0.0-beta.11`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.0.0-beta.11) adds support for Firestore through redux-firestore.

[The Firestore section](http://docs.react-redux-firebase.com/history/v2.0.0/docs/firestore.html) has also been added to the docs with info about Profile and queries stuff.

Please feel free to open issues/pull requests if the docs are not clear or you find an issue with functionality. Enjoy!
