### ISSUE TITLE
bug(docs): HOCs applied in inconsistent order within examples

### ISSUE THREAD

**Issue by drexkdal** [prescottprue/react-redux-firebase#321]
In the documentation, examples show `firebaseConnect` applied to a component first and then `connect` applied to the resulting higher order component (`fbWrapped`). Decorators are written in the same sequence.

However, `compose` applies its arguments from right to left. So `connect` and `firebaseConnect` are applied in reverse order in the examples where `compose` is used. 

It's confusing when reading the docs, but it also adds an annoying element of uncertainty when something doesn't work as expected.

**Comment by prescottprue** [comment]
@drexkdal Great call. Will work on making this more consistent.

**Comment by prescottprue** [comment]
@drexkdal Just to note, order shouldn't really matter, if you find a situation where it does, please file an issue.

Was there a specific place in the docs that you saw the inconsistency? Just want to make sure I clear it up everywhere.

**Comment by drexkdal** [comment]
I am mildly surprised that `connect` and `firebaseConnect` seems to be commutative. I don't think that rule applies to all HOCs, but it's worth a thought.

Sorry, but I can't remember exactly on which pages I saw the examples. Everywhere `compose` is used, I suppose?

**Comment by prescottprue** [comment]
@drexkdal I believe what you are saying about "reverse order" may be incorrect. Both decorators and compose follow the same order meaning that they wrap from bottom to top.

It can be shown with a simple example and using react-dev-tools:

**decorators**
```jsx
@firebaseConnect(['todos'])
@connect(({ firebase }) => ({
  todos: firebase.data.todos,
}))
export default class HomeDecorated extends Component {
  render() {
    return <div></div>
  }
}
```
In dev tools:

![image](https://user-images.githubusercontent.com/2992224/32585452-6950748a-c4b2-11e7-9156-8fb548047b97.png)


**compose**
```jsx
const HomeWrapped = () => <div></div>

export default compose(
  firebaseConnect(['todos']),
  connect(({ firebase }) => ({
    todos: firebase.data.todos,
  }))
)(HomeWrapped)
```

In dev tools:

![image](https://user-images.githubusercontent.com/2992224/32585385-0dd2d0e4-c4b2-11e7-9038-cfb9eac6f66c.png)


Which makes sense, because as mentioned, it goes from **right to left** (i.e. bottom to top) the same order as decorators.

**Comment by drexkdal** [comment]
You're absolutely right, of course.
