### ISSUE TITLE
React Native Firebase 3.0?

### ISSUE THREAD

**Issue by Jonovono** [prescottprue/react-redux-firebase#330]
Hi. Does this library work with react native firebase version 3?

**Comment by prescottprue** [comment]
@Jonovono It should, you will have to use `react-redux-firebase v2` [as described in the react-native section under native-modules](http://docs.react-redux-firebase.com/history/v2.0.0/docs/integrations/react-native.html#native-modules).

Is it not working as expected? If so we can reopen this.

Feel free to [reach out over gitter](https://gitter.im/redux-firebase/Lobby) if you have questions since you will most often get a quicker response that way.

**Comment by Jonovono** [comment]
Awesome, thanks. I may have spoke too soon. I'm getting tonnes of errors but think they are just related to updating react/react-native in my project. 😢
