### ISSUE TITLE
bug(withFirebase): "Warning: Failed child context type..." when using react v16

### ISSUE THREAD

**Issue by canyavall** [prescottprue/react-redux-firebase#337]
Hi there!

First of all, ty very much for this library, I'm enjoying it a lot.

Actually, I'm doing some testing with the version 2.0..-beta16, everything is working but, when I'm loading the firebase functions with "withFirebase()" I get the message:
proxyConsole.js:54 Warning: Failed child context type: Cannot read property 'store' of undefined

Maybe I'm doing something wrong but, I don't think so as the library is pretty simple to be used...

This is the code link: [Code](https://github.com/canyavall/soulshards/blob/master/src/components/ResourceAdd/index.js)

**Comment by prescottprue** [comment]
It seems that this may be an issue of using `recompose` and `react v16` not playing nice as far as context types. Only able to replicate on react v16, so I wonder if context is handled in a different way (possible even involving `react-redux`)?

Not sure which it is (`recompose`/`react-redux` or both), but depending on how quickly it can be addressed we may have to switch `withFirebase` to a custom Class (similar to `firebaseConnect`). 

In the meantime you can use `firebaseConnect()` (no arguments passed) to accomplish the same thing that `withFirebase` does.

**Comment by canyavall** [comment]
Perfect, thank you very much!

I'll check it when I can as I0ve to finish some things

By the way, thank you very much for the library, it is just awesome

**Comment by prescottprue** [comment]
@canyavall The [PR for v2.0.0-rc.1](https://github.com/prescottprue/react-redux-firebase/pull/358) includes changes where `withFirebase` and `withFirestore` use classes directly instead of `recompose`'s `withContext`.

Feel free [to npm link it](http://docs.react-redux-firebase.com/history/v2.0.0/docs/contributing.html#npm-linking) and give it a try yourself, but I was able to get it running with React 16. The plan for now is going to be to stick to this way of doing things until `recompose`'s `withContext` supports React 16.

**Comment by canyavall** [comment]
Perfect, I'll try it, sorry to don't answer before, I'm out of time actually ^_^

**Comment by canyavall** [comment]
Checked and fixed, thx man!
