### ISSUE TITLE
Developer is able to use a "Data loading" flag to let user know data is still being loaded

### ISSUE THREAD

**Issue by sshadmand** [prescottprue/react-redux-firebase#340]
**Do you want to request a *feature* or report a *bug*?**  

Feature: Some way of showing the user that the data is still being received from firebase. 

**What is the current behavior?**

Firebase state shows some variables but nothing (as far as I can tell) that tells me when something is still loading. 

**What is the expected behavior?**

Data in the state that tells me "loading: true" so I may show a spinner until it completes.

**Comment by prescottprue** [comment]
@sshadmand This already exists in few  different flavors

### Helpers

There are the `isLoaded` and `isEmpty` helpers (as shown [in the use section of the README](https://github.com/prescottprue/react-redux-firebase#use)).

These work by checking if the value that is passed to them is `undefined` or `null` (in this case the prop which is the part of state associated with the data you are loading) . `undefined`, means it has not yet been loaded (all paths before you put anything into them), `null` means that it has been loaded and there is nothing there. If there is a value there, then the data has loaded (data is an Immutable JS map if you are using `v1.*.*`, whereas it will just be the value that lives in Firebase for `v2.0.0`).

### Manual
Since it is really just that simple difference, many go without the `isLoaded` and `isEmpty` helpers all together.

### Meta Info In State
They are much less often used, but there are also meta records in state about when certain paths are loading and loaded which live in state under:

* `requesting`
* `requested`
* `timestamps`

Note that these are stored by string key instead of nested like the data (which is nested to match Firebase structure).

I have noted that this should be more clear in the docs so something may be added soon. Going to close the issue for now since this is an existing feature. If you implementation questions, you may get quicker responses [over the gitter channel](https://gitter.im/redux-firebase/Lobby).
