### ISSUE TITLE
Support for firestore querying

### ISSUE THREAD

**Issue by phillyfan1138** [prescottprue/react-redux-firebase#343]
It would be awesome to support more advanced querying like that described in the following firestore document:

https://firebase.google.com/docs/firestore/query-data/get-data

Currently, it appears that only basic querying based of the url is supported.

**Comment by phillyfan1138** [comment]
Never mind, it appears it is supported...are there any docs on this?  I got it to work using inside the firestoreConnect function:

`[
        { 
            collection: `apps`, 
            where: ['uid', '==', store.getState().firebase.auth.uid] 
        }
 ]`

**Comment by prescottprue** [comment]
The [Firestore section of the docs](http://docs.react-redux-firebase.com/history/v2.0.0/docs/firestore.html) is where the notes on this live for now. There will be more documentation coming in the future. 

If you have any questions or want to bounce ideas around while implementing, feel free to join us on the [redux-firestore gitter channel](https://gitter.im/redux-firestore/Lobby).


Sidenote: BE CAREFUL USING STORE IN `firestoreConnect` and `firebaseConnect`.... Things may not re-render as you expect since re-renders occur on prop changes **NOT** on auth state change. This means you will want to load auth before running a component with the query config you provided. The [state based query example](https://github.com/prescottprue/react-redux-firebase/blob/v2.0.0/examples/snippets/stateBasedQuery/Home.js#L6-L17) shows loading auth and passing it as a prop.
