### ISSUE TITLE
v2 non-immutable issue with firestore example

### ISSUE THREAD

**Issue by TimMeade** [prescottprue/react-redux-firebase#348]
We use an immutable store and are trying to integrate v2 for firestore access.   

The issue comes from this bit in Home.js

connect(
    ({ firestore }) => ({
      todos: firestore.ordered.todos,
    })
  ),

this does not work at all with immutable store.   I found the reference for using getVal, but have tried multiple iterations of it and nothing seems to work.

Is there a simple way to use immutable store?  An example of this?

Much thanks.

**Comment by TimMeade** [comment]
Closed as seems i was not on v2 examples.

**Comment by prescottprue** [comment]
@TimMeade this may be an issue for [redux-firestore](https://github.com/prescottprue/redux-firestore). I am assuming you mean ImmutableJS and not general "immutablability" as ([since redux requires an immutability](https://redux.js.org/docs/faq/ImmutableData.html#why-is-immutability-required)). v1 of react-redux-firebase actually used Immutable internally, but for v2 we moved away from that (for a number of reasons).

It would be great to support immutable for v2, but an integration/example does not yet exist (open to PRs though).

Just a thought based on past experience (also mentioned in [redux getting started](https://redux.js.org/#the-gist)): Could you run a store made up of different types? Since the firestore stuff for v2 stands alone, that section could be a normal JS object, then have the other parts of your store be immutable maps.

**Comment by TimMeade** [comment]
I had similar thoughts on the store with different types.    Been a long day, I'll look into it tomorrow and get back.  Was hoping i had missed something simple.

**Comment by prescottprue** [comment]
Going to close because the scope is so large for now. May look into this again in the future, especially if there is more interest in using Immutable (though it mostly seemed to cause confusion).

Open to PRs if anyone is interested.
