### ISSUE TITLE
firestoreConnect does not update on props change

### ISSUE THREAD

**Issue by Klabauterman** [prescottprue/react-redux-firebase#365]
I am using firestoreConnect with paths that depend on the component props, but the listeners do not get updated when the props for the paths change.

Are there plans to fix this issue in the near future?

**Comment by prescottprue** [comment]
@Klabauterman Can you provide a replication? What version are you using? Is the path of the listener itself changing or just query params?

Re-rendering not occurring is not expected behavior. There are many production applications (including multiple my company is running) that use this re-rendering based on props.

**Comment by Klabauterman** [comment]
@prescottprue It looks like it was fixed already I just updated from redux-firestore from 0.2.2 to 0.2.5 and react-redux-firebase from 2.0.0-beta.17 to 2.0.0-rc.1 and now it seems to work :).
