### ISSUE TITLE
Bug(Listeners): Component with same listeners does not update correctly.

### ISSUE THREAD

**Issue by karltaylor** [prescottprue/react-redux-firebase#368]
**What is the current behavior?**

I have two containers with the same structure.

```javascript
@connect(({ firebase: { auth, profile } }) => ({
  auth,
  profile
}))
export default class ContainerOneWrapper extends Component {
  render() {
    return (
      <ContainerOneComponent
        router={this.props.router}
        profile={this.props.profile}
        auth={this.props.auth}
      />
    )
  }
}
```

```javascript
@connect(({ firebase: { auth } }) => ({
  auth
}))
export default class ContainerTwoWrapper extends Component {
  render() {

    return (
        <ContainerTwoComponent auth={this.props.auth} />
    )
  }
}
```

They both have the same listeners on them,

ComponentOne
```javascript
@firebaseConnect(({ auth }) => [
  `/cookbooks/${auth.uid}`,
  `/planners/${auth.uid}`
])
@connect(({ firebase: { data, auth } }) => ({
  userMeals: data.cookbooks && data.cookbooks[auth.uid]
}))
```

ComponentTwo
```javascript
@firebaseConnect(({ auth }) => [
  `/cookbooks/${auth.uid}`,
  `/planners/${auth.uid}`
])
@connect(({ firebase: { data, auth } }) => ({
  userMeals: data.cookbooks && data.cookbooks[auth.uid],
  userPlan: data.planners && data.planners[auth.uid]
}))
```

When I navigate to ComponentOne, it sets the listeners fine, 

![](https://cdn.pbrd.co/images/H0jp23T.png)

But then I go to ComponentTwo, and the listeners are `UNSET`, but the componentTwo listeners are not set.

![](https://cdn.pbrd.co/images/H0jpS1L.png)

And then if I go back to ComponentOne:

![](https://cdn.pbrd.co/images/H0jqnoV.png)

**What is the expected behavior?**

When navigating to a different component the listeners should unset and on the new component rendering, set the correct listeners, even if they're the same? 🤷🏻‍♂️

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

using `"react-redux-firebase": "^2.0.0-rc.2"`

**Comment by kylepotts** [comment]
I am having a similar issue. Using the 2.0 version. Kinda makes using this pointless since nothing updates.

**Comment by prescottprue** [comment]
Looking into this. Haven't replicated yet, but will post any updates here.

@karltaylor So that I correctly replicate - Were you no longer receiving updates in that collection (i.e. listener actually detached) or were you just seeing the `UNSET_LISTENER` action dispatched? Trying to figure if the dispatches are erroneous or if the listeners are actually being detached.

@kylepotts Same questions to you. 


Thoughts before diving in:
* Obviously seems to relate to something to do with how listeners are being compared/set/unset
* It could be either erroneous (should not be happening) dispatches, or the listeners are actually being detached
* If the queries are different or write to different places in redux then hopefully this would go away - thought is if they have different `queryParams` or `storeAs` the comparison won't be an issue?

**Comment by karltaylor** [comment]
Hey @prescottprue thanks for looking into this! 

I was no longer receiving updates in that collection, so it's definitely detatched. 

@kylepotts for a part time fixed I just added a `watchEvent` on `componentDidMount`. It adds the listeners again for me and works ok. Probs not the best solution...

```javascript
componentDidMount() {
    this.props.firebase.watchEvent('value', `/cookbooks/${this.props.auth.uid}`)
    this.props.firebase.watchEvent('value', `/planners/${this.props.auth.uid}`)
}
```

**Comment by kylepotts** [comment]
@prescottprue I can do some digging around and let you know. 

Pretty much on every page I have I have two things in the firebaseConnect() which are always the exact same thing.

**Comment by kylepotts** [comment]
Just an update adding a different store as seemed to make it work just fine.

**Comment by abjorck** [comment]
Got the same issue, it looks like. I found that reloading the browser while on a "working" component, it stopped working and hung waiting for data - I see it unset_listener before data arrives.

**Comment by prescottprue** [comment]
@abjorck Good to know. Something to note: `storeAs` fixes the issue for some

**Comment by prescottprue** [comment]
I have been looking into passing options to `firebaseConnect` for not calling `UNSET_LISTENER` for certain listeners - it has some implications though.

**Comment by karltaylor** [comment]
Do you have time to elaborate? Could potentially look into it

**Comment by prescottprue** [comment]
@karltaylor What I was getting at is that query settings could prevent [the `unsetWatcher` call within componentDidUnmount of `firebaseConnect`](https://github.com/prescottprue/react-redux-firebase/blob/master/src/actions/query.js#L42-L48) maybe something like:

```js
// NOTE: THIS IS NOT REAL SYNTAX - EXAMPLE
firebaseConnect(() => [
  { path: 'some', unsetWatcher: false }
])
```

The more I think about it though, it may be better to approach it by intentionally allowing multiple listeners at the same path (which is [currently prevented here](https://github.com/prescottprue/react-redux-firebase/blob/master/src/actions/query.js#L42-L48)).

Regardless of how it is approached, it seems like this may be a breaking change for some, so if it warrants v3.0.0 anyway then maybe we should take the opportunity to switch to storing the listener [callbacks by key similar to redux-firestore](https://github.com/prescottprue/redux-firestore/blob/master/src/utils/query.js#L227) - where right now they are [tracked by a count of listeners on that path](https://github.com/prescottprue/react-redux-firebase/blob/master/src/utils/query.js#L100-L104).

**Comment by prescottprue** [comment]
#429 also mentions using typescript for v3, which is an interesting idea that I wanted to make sure was noted.

**Comment by iamthefox** [comment]
hi @prescottprue, I've compiled a quick example how to replicate this issue. You can have a look at it [here](https://github.com/iamthefox/firebase-router-example/tree/master/src). 

I think it is caused by a race conditions within react's lifecycle methods. 

firebaseConnect is using willComponentMount and willComponentUnmount set/unset listeners. 

This causes following chain of events when using it in combination with the react-router:

1. ComponentA invokes componentWillMount and creates a listener `foo`
2. Route switch
3. ComponentB componentWillMount kicks in before willUnmount of the previous component. It sees an existing listener and does nothing. 
4. ComponentA invokes componentWillUnmount and cleans up after itself while deleting listeners that belong to a ComponentB as well. 

Potential solution:
Move watchEvents logic to componentDidMount rather than componentWillMount  as per description [here](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#fetching-external-data). I will give it a test later today to see if it causes any issues with our product.

**Comment by iamthefox** [comment]
To expand on the example above, 

This is how redux inspector looks when firebaseConnect is invoking componentWillMount

![screen shot 2018-04-03 at 3 07 58 pm](https://user-images.githubusercontent.com/11770969/38230417-18d00dec-3751-11e8-9f65-4b0510a10903.png)

And this is how it looks if I replace it with componentDidMount.

![screen shot 2018-04-03 at 3 07 27 pm](https://user-images.githubusercontent.com/11770969/38230431-2c771f48-3751-11e8-85e1-fb3f23519724.png)

I can't tell what this could possibly affect, but for me personally it makes more sense to have it in didMount rather than willMount since it does not really bring any performance gains.

**Comment by prescottprue** [comment]
@ShayMatasaro `storeAs` is the current way to give listeners a unique identifier, so you could go that route.

I don't believe it is a race condition, but instead that the incorrect number of listener callbacks are being/remaining attached. Since the callbacks for the listeners write data into redux, sometimes you want multiple callbacks (in the case of multiple of the same query going to different paths in redux) other times you want a single callback (in the case of multiple components with the same query that places data in the same place of redux).

This is currently one of the highest priority issues. Looking into it is planned to get attention this week and next.

All should feel free to continue to reach out if they are experiencing this or with PRs.

**Comment by towfiqi** [comment]
@prescottprue Still having this issue. `storeAs `didn't help. Is doing something like this (posted above) has any negative impact? like invoking multiple listeners on route change or any performance issue?

```
componentDidMount() {
    this.props.firebase.watchEvent('value', `/cookbooks/${this.props.auth.uid}`)
    this.props.firebase.watchEvent('value', `/planners/${this.props.auth.uid}`)
}
```

Thanks

**Comment by santiago-elustondo** [comment]
Hey, @prescottprue

The issue is that when 2 components use `firebaseConnect()` to watch the same path, the first one to unmount will remove that path from the listeners, leaving the other disconnected. 

If we use `storeAs` then the given store key is appended to the path id, like `values:/users@<<storeKey>>`. If the 2 components above use different store keys, then they will only remove their own path id when unmounting, and not interfere with the other's. 

This might be a workaround in some cases, but not an actual solution. We are now downloading and storing the data twice, under 2 different keys, in `firebase.data`. If all components apply their own `storeAs` key, to safeguard their subscription, then they can't benefit from some of the data they are interested in being possibly already loaded by another component before.

Possible solutions -----

We could have have is another option similar to `storeAs` that only performs the path id concatenation step, but routes the downloaded data to the default location, or to an independently identified location (perhaps using `storeAs`). Maybe an option like `withId`, so you could call it like.
```
// NOT REAL SYNTAX
firebaseConnect((props) => ([
  [{ path: 'users' , withId: 'profileComponent' }
]),
```
Which would produce the following `firebase.listeners.allIds` in the redux store
```
0: "value:/users$profileComponent"
1: "value:/users$searchComponent"
```

Otherwise we could just append the subscribing component's name automatically, or keep a counter of how many components are currently listening to a particular path, so that we don't get rid of it until it's 0, like in garbage collection strategies.

**Comment by santiago-elustondo** [comment]
> right now they are tracked by a count of listeners on that path.
@prescottprue, this is not working properly. ^
I didn't realize you already had already done this.

**Comment by prescottprue** [comment]
It seems like this issue is fixed for `firebaseConnect` in [`v2.1.0`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.1.0).

Thanks to @cworf to the PR to fix.

If anyone still experiences these symptoms or something similar after upgrading, please reach out.

**Comment by karltaylor** [comment]
👏

**Comment by omrihaim** [comment]
> If anyone still experiences these symptoms or something similar after upgrading, please reach out.

Hey @proscottprue, I still encounter this issue :/

**Comment by prescottprue** [comment]
@omrihaim could you possibly open up a new that lists the versions you are using to bump it to the top? It can also point to this issue for reference.
