### ISSUE TITLE
Error: "This operation is not supported in the environment this application is running on"

### ISSUE THREAD

**Issue by banerjed** [prescottprue/react-redux-firebase#39]
Hi - getting this error when running on a Mac. Not sure if I am doing something incorrect (fairly new to this) - using the latest 1.2 version of the library.

Exact error message in the Simulator is
_This operation is not supported in the environment this application is running on. "location.protocol" must be http or https and web store must be enabled._

My store code looks like the following which is what causes the error to trigger (haven't even written any of the component code yet).

export default function configureStore(onCompletion:()=>void):any {
  const enhancer = compose(
    applyMiddleware(**thunk.withExtraArgument(getFirebase)**, promise),
    **reactReduxFirebase(firebaseConfig, {userProfile: 'users', enableLogging: false}),**
    devTools({ name: 'groceries', realtime: true})
  );

  const store = createStore(reducer, enhancer);
  persistStore(store, { storage: AsyncStorage }, onCompletion);

  return store;
}

Code: https://github.com/banerjed/MobileStarter

thanks

**Comment by prescottprue** [comment]
Are you using react-native? This library is currently not supported with react-native due to firebase's library not being fully supported.

However, if you provide `enabledRedirectHandling: false` to your config, you should be able to use other parts of the library (redirect auth requires http/https, which react-native does not currently support).

Try this config:

```js
const enhancer = compose(
  applyMiddleware(thunk.withExtraArgument(getFirebase), promise),
  reactReduxFirebase(
    firebaseConfig,
    { userProfile: 'users', enabledRedirectHandling: false }
  ),
  devTools({ name: 'groceries', realtime: true})
);
```

The hope is to make everything react-native compatible far in the future, but it will take Firebase's JS library being supported to make that happen.

If you are sticking with react-native, I would check out [react-native-firestack](https://github.com/fullstackreact/react-native-firestack). The author is a super cool guy, and is always available to answer questions/issues.

**Comment by banerjed** [comment]
Thanks for the pointer...

**Comment by Sigura** [comment]
got same issue in safari under selenium tests (safari renew driver)

```
react-redux-firebase.js:7356:1963 Error: This operation is not supported in the environment this application is running on. "location.protocol" must be http or https and web storage must be enabled.
```

**Comment by prescottprue** [comment]
@Sigura A few things:
* Are you sure you followed the setup above including setting `enabledRedirectHandling: false`?
* Did you include XMLHttpRequest as is [done in the tests](https://github.com/prescottprue/react-redux-firebase/blob/v1.4.0/tests/setup.js#L22-L23):
```js
// needed to fix "Error: The XMLHttpRequest compatibility library was not found." from Firebase auth
global.XMLHttpRequest = require('xmlhttprequest').XMLHttpRequest
```
  **Note:** Needed since Firebase uses `XMLHttpRequest` internally (browsers have it by default). This has also been discussed [in the ssr issue](https://github.com/prescottprue/react-redux-firebase/issues/72), and will be  included in the docs before `v1.4.0` is released.

**Comment by Sigura** [comment]
> Are you sure you followed the setup above...

absolutely

**Comment by Sigura** [comment]
looks like it is for server side (

```
ERROR in ./~/xmlhttprequest/lib/XMLHttpRequest.js
Module not found: Error: Can't resolve 'child_process' in '.../node_modules/xmlhttprequest/lib'
resolve 'child_process' in '.../node_modules/xmlhttprequest/lib'
  Parsed request is a module
```

**Comment by prescottprue** [comment]
@Sigura Can you possible share a repo with me where I could reproduce what you are seeing. It will help speed up the debugging process if I can verify for sure.

**Comment by Sigura** [comment]
I see this issue in very-very specific environment: Safari 10.1 under selenium driver

and no, there is private repo (

found same report https://github.com/angular/angularfire2/issues/554

**Comment by prescottprue** [comment]
@Sigura There was a typo in my last post `enabledRedirectHandling` should be `enableRedirectHandling` (notice that "enable" is not "enabled").

Try removing `xmlhttprequest` and changing to `enableRedirectHandling: false` in your config, then let me know.

**Comment by Sigura** [comment]
@prescottprue Thank you! It works perfectly now!

**Comment by prescottprue** [comment]
@Sigura Great to hear. As stated, this will be in the docs for `v1.4.0`
