### ISSUE TITLE
feat(firestoreConnect): firestoreConnect HOC de-dupes listeners automatically

### ISSUE THREAD

**Issue by Venryx** [prescottprue/react-redux-firebase#392]
**Do you want to request a *feature* or report a *bug*?**  

Report a bug/inconsistency.

**What is the current behavior?**

Having two components both use `firestoreConnect` on the same paths, causes `setListener` to be called two times. This means `onSnapshot` is called for that path twice, retrieving the same data but as a "second instance".

This is problematic because my code relies on the objects in `firestore/data` remaining identical/the-same-instance if the data has not changed.

That is, `store.firestore.data.myObject` should be "===" identical to its previous value, if the only thing that has happened since the last access was that a new component connected/set-listeners for that path.

**What is the expected behavior?**

The expected behavior is for the `firestoreConnect` higher-order-component/wrapper to keep track of how many components are currently "listening" on a path, and to not add another listener/`onSnapshot`-call if there's one already set for that path. (since the `onSnapshot` call otherwise ends up overwriting the data at that path with the same data/shape but as a new copy/instance)

This is what is currently done in the `firebaseConnect` HOC (through the `watchEvents` system), and I wonder why this functionality was not also implemented in the `firestoreConnect` HOC as it seems very useful for performance reasons. (it lets you do a shallow compare to see if data at a path has changed, which my software relies on heavily to maintain good performance, since it has a "higher level" data-transformation-with-caching system in place)

**Comment by Venryx** [comment]
Until an official fix has landed, I have implemented a quick implementation of the listener-count tracking, as seen below:
```
let pathListenerCounts = {};
function SetListeners(listeners) {
	for (let listener of listeners) {
		let path = ListenerQueryOptionsToPath(listener);
		let oldListenerCount = pathListenerCounts[path] || 0;
		pathListenerCounts[path] = oldListenerCount + 1;
		if (oldListenerCount > 0) continue;

		store.firestore.setListener(listener);
	}
}
function UnsetListeners(listeners) {
	for (let listener of listeners) {
		let path = ListenerQueryOptionsToPath(listener);
		pathListenerCounts[path]--;
		if (pathListenerCounts[path] == 0) {
			store.firestore.unsetListener(listener);
		}
	}
}
```

To use, just replace all calls to `firestore.setListeners` and `firestore.unsetListeners` in the `firestoreConnect.js` file with calls to the `SetListeners` and `UnsetListeners` functions above.

Actually, on second look it appears I'm making use of a custom `ListenerQueryOptionsToPath` function. I'll supply that as well:
```
export function ListenerQueryOptionsToPath(listenerPath: any) {
	let result = [];
	let pathNodes = [listenerPath].concat((listenerPath.subcollections || []));
	for (let pathNode of pathNodes) {
		result.push(pathNode.collection);
		if (pathNode.doc) {
			result.push(pathNode.doc);
		}
	}
	return result.join("/");
}
```

**Comment by prescottprue** [comment]
@Venryx Its great to see the examples. `firestoreConnect` should definitely make use of this since many depend on the same performance gain/simple comparison you are mentioning.

Open to a PR, but if you don't get to it, this will definitely be on the list for an upcoming release.

##### Aside About Performance
The interesting thing is that there isn't always the much of a "performance gain" (or at least my team has found in our diagnosing of performance issues in our production application). If you are correctly using state selectors and preventing unnecessary prop changes (through `PureComponent` and other methods of props comparison) then everything should not re-render if the same data is written into redux by another listener.

You might then ask - well what about all of those extra listeners? Talking to the Firebase team multiple times has informed me of the fact that their JS library actually manages listeners under the hood (makes sense). That means that you aren't making unnecessary listeners either.

So as far as "bad performance" there is still the potential for extra dispatches, which are a result of the multiple callbacks we registered - bringing us back to how/why we are tracking them like we do with `firestoreConnect`. That way we can intentionally make multiple callbacks that send data to different parts of redux (as in the case of using `storeAs` or `populate`).

All of this reminds me that there should probably be something clarifying all of this in the docs. It could also easily point to some state selector examples.

**Comment by prescottprue** [comment]
@Venryx Just for an update: [the current progress for `v0.3.0` of redux-firestore](https://github.com/prescottprue/redux-firestore/pull/62) includes logic that does not attach multiple listener callbacks.

The `allowMultipleListeners` config option is also in there for enabling/disabling whether multiple listeners are attached for the same query (as some may want to do this intentionally) - it can be either Boolean or Function.

Going to wait to close this until that is merged, but testing it went well so it should be in soon.

**Comment by prescottprue** [comment]
[`v0.3.0` of `redux-firestore` was released](https://github.com/prescottprue/redux-firestore/releases/tag/v0.3.0) with improved listener tracking as mentioned.

For those hoping to enable multiple listener callbacks for a single query remember there is the `allowMultipleListeners` config option (accepts a Boolean or Function).

Thanks for reporting!

**Comment by compojoom** [comment]
@prescottprue - I just realised that we have to set allowMultipleListeners to true. Thought that we would have this turned on by default?

Can you explain how your code works? It looks different than what @Venryx suggested.
You do this:
```
/**
 * Set an array of listeners only allowing for one of a specific configuration.
 * If config.allowMultipleListeners is true or a function
 * (`(listener, listeners) => {}`) that evaluates to true then multiple
 * listeners with the same config are attached.
 * @param {Object} firebase - Internal firebase object
 * @param {Function} dispatch - Redux's dispatch function
 * @param {Array} listeners
 */
export function setListeners(firebase, dispatch, listeners) {
  if (!isArray(listeners)) {
    throw new Error(
      'Listeners must be an Array of listener configs (Strings/Objects).',
    );
  }

  return listeners.forEach(listener => {
    // Config for supporting attaching of multiple listeners
    const { config } = firebase._;
    const multipleListenersEnabled = isFunction(config.allowMultipleListeners)
      ? config.allowMultipleListeners(listener, firebase._.listeners)
      : config.allowMultipleListeners;
    // Only attach listener if it does not already exist or
    // if multiple listeners config is true or is a function which returns
    // truthy value
    if (!listenerExists(firebase, listener) || multipleListenersEnabled) {
      setListener(firebase, dispatch, listener);
    }
  });
}

```

As far as I understand you always trigger "SET_LISTENER", where the @Venryx  code did it just once. But the part that I don't understand is the detaching of the listener.
```

/**
 * @description Remove/Unset a watcher
 * @param {Object} firebase - Internal firebase object
 * @param {Function} dispatch - Redux's dispatch function
 * @param {Object} meta - Metadata
 * @param {String} collection - Collection name
 * @param {String} doc - Document name
 */
export function detachListener(firebase, dispatch, meta) {
  const name = getQueryName(meta);
  if (firebase._.listeners[name]) {
    firebase._.listeners[name]();
    delete firebase._.listeners[name]; // eslint-disable-line no-param-reassign
  }

  dispatch({
    type: actionTypes.UNSET_LISTENER,
    meta,
    payload: { name },
  });
```

You don't check if the listener needs to be detached or not. As far I understood the code - getQueryName won't give you an unique name for each attached listener.

How is this working? Because it seems to work... but I don't understand the magic behind it...
