### ISSUE TITLE
Bundling requested data

### ISSUE THREAD

**Issue by ralcon** [prescottprue/react-redux-firebase#394]
Hi there...

For my Firebase Database structure...

```
- tasks
  - taskOne
    - // properties of taskOne
  + taskTwo
```

... the following code ...

```
firebaseConnect((props, store) => {
      let myTaskQueries = props.taskIds.map((taskId) => {
        return {
          path: 'tasks',
          queryParams: ['orderByKey', 'equalTo=' + taskId],
          storeAs: `tasks/${taskId}`
        }
      })
      return myTaskQueries
    }
  )
```

... gives me a little confusing output in state.firebase.data! It is like this:

```
firebase: Object
  |- data: Object
    |- tasks: Object
      |- taskOne: Object // unnecessary level
        |- taskOne: Object 
          |- // properties of taskOne
```
How do i bundle the requested tasks without the extra 'level'?

**Comment by ralcon** [comment]
If i change ``` storeAs: `tasks/${taskId}` ``` to ``` storeAs: `tasks` ``` i get the expected structure, but with only one task (only with the last queried task).

**Comment by prescottprue** [comment]
@ralcon The query you are showing actually queries the **whole tasks list** for a task that matches the provided id instead of querying for **just that task**.

Since you are using `orderByKey` it seems like you are trying to just select tasks by key. Is there a reason that you can not just query by key? Looking something like so:

```js
firebaseConnect((props, store) => {
  return props.taskIds.map((taskId) => {
        return {
         path: `tasks/${taskId}`
        }
   })
})

```

That way you are querying each task by key and they will all be placed in `state.firebase.data.tasks`.

Let me know if I am mis-understanding what you are trying to accomplish.

**Comment by ralcon** [comment]
That was my goal to accomplish! Thx
