### ISSUE TITLE
`UpdateProfile` method does not exist on `firebase` in the store

### ISSUE THREAD

**Issue by cosminstefanxp** [prescottprue/react-redux-firebase#404]
**What is the current behavior?**
Trying to access `store.getState().firebase.updateProfile({...})` ends up throwing a TypeError:
> TypeError: store_1.store.getState(...).firebase.updateProfile is not a function

**Replication steps:**
- Try to use: `store.getState().firebase.updateProfile({...})`

**What is the expected behavior?**
Isn't `updateProfile()` supposed to be available on that instance as well? If not, I believe this should be better spec'd in the documentation.

**Comment by prescottprue** [comment]
@cosminstefanxp This is expected behavior. What you have grabbed is firebase from redux state (i.e. `state.firebase`), when instead you want `store.firebase` (which is attached by the `reactReduxFirebase` store enhancer)

It is uncommon to store objects with methods on them within redux state.

`store.firebase` should work for your purposes, but if you need it elsewhere (i.e. in thunks/sagas) checkout [the docs example showing use of `getFirebase`](http://react-redux-firebase.com/docs/integrations/thunks.html).
