### ISSUE TITLE
Mention of the original repo

### ISSUE THREAD

**Issue by RahavLussato** [prescottprue/react-redux-firebase#413]
hi @prescottprue ,
most of the code base here are taken from [redux-react-firebase](https://github.com/tiberiuc/redux-react-firebase), i see a lot of my code here that don't have my mention on the original commit because you copy pasted the code and change the files names and structure.
i saw that you have Contributors section on the readme but this is auto generated base on the commits on your fork and don't have the data about the original commits and contributors.

i think that at least it worth mention on the readme that this project is based on [redux-react-firebase](https://github.com/tiberiuc/redux-react-firebase).

i know that you did a lot of changes and add new stuff on [redux-react-firebase](https://github.com/tiberiuc/redux-react-firebase) for the community but still it'll be nice to see some mention because there is still a lot of code from the original repo here.

**Comment by prescottprue** [comment]
Hey, long time! Thanks for reaching out.

Some of the original ideas for the `v1.*.*` version came from your repo, but the current version `v2.*.*` was actually quite a different beast (there is no usage of immutable). There is also quite a bit different (even in the v1 series) as far as things like `populate` and `profileParamsToPopulate`.

Regardless of their differences - the README actually contained a direct reference to your repo before, but since the README was getting long, the [FAQ section (where your repo is referenced)]( http://react-redux-firebase.com/docs/FAQ.html) was moved to the docs.

In that section I explain why things branched off (mostly based in a need for features that were quite a change). At the time of needing that stuff it seemed like there wasn't much movement on your repo (had a PR)

I want to make sure to give thanks where it is due - lets chat [over gitter](https://gitter.im/redux-firebase/Lobby).

**Comment by RahavLussato** [comment]
Hi,
just to clarify this if you wasn't copy pasted the code on this [commit](https://github.com/prescottprue/react-redux-firebase/commit/aa32dcd146780e6f9faf187316c155066932131a) i was totally ok with the fact that there is no mention on the readme, but because you copy pasted a lot of code without it history (you didn't created this repo from the original one, you copy pasted the code and this action don't include the history of the commits) i think that it must to have a mention on the readme file.
