### ISSUE TITLE
feat(core): IE10 support

### ISSUE THREAD

**Issue by Ionut-Milas** [prescottprue/react-redux-firebase#424]
Hi @prescottprue.
Under IE10 the lib has a problem.
have a look at this image: https://ibb.co/eJGa07

**Comment by prescottprue** [comment]
@Ionut-Milas Currently the babel config is set to build for `chrome 52` and `safari >=7`. I'm open to changing the config to make things work for IE. My one fear is not fully understanding the impact that may have as far as breaking changes, so lets look into that.

As for methods around it for now - I would suggest forking and [linking your local build (as described in the linking docs)](http://react-redux-firebase.com/docs/contributing.html#npm-linking) and trying to change [the babel targets](https://github.com/prescottprue/react-redux-firebase/blob/master/.babelrc#L5-L9). Once you get something that works for the environments you need, you can use that version while we work on a PR.

My guess is that it will have to make it in to v2.1.0 or later, but that will depend of what changes.

**Comment by prescottprue** [comment]
@Ionut-Milas After looking closer it seems like the issue is internal to the Firebase library. Are you sure you are running the most updated Firebase JS SDK?

That suspicion was further confirmed when looking at the debug output of `babel-preset-env`, which indicates that currently the targets are configured to include `ie: 10`:

![image](https://user-images.githubusercontent.com/2992224/39343560-625e5dd0-4992-11e8-9b64-bbaf90e9a982.png)


Going to close since there isn't much that can be done to fix something within the Firebase lib itself. We can reopen if there is a way to replicate the issue not appearing until adding `react-redux-firebase`. Thanks for reporting!

**Comment by Ionut-Milas** [comment]
Thanks for the update.
