### ISSUE TITLE
Fetching and displaying a single document. How to improve this?

### ISSUE THREAD

**Issue by 0x80** [prescottprue/react-redux-firebase#429]
I created an admin interface that needs to go over user profiles one by one, for which I wrote a generic `FetchUserProfile` component. The idea is simple. You give it a userId as props, it uses that to fetch the profile data, and when the data is available the children are called with the data. (This is the Function as Child pattern as described for example [here](https://medium.com/merrickchristensen/function-as-child-components-5f3920a9ace9))

The code below is using Typescript. Please just ignore any syntax that is outside of Javascript. It is not the point.

The code below is working yet there are a lot of things wrong with it from an architectural point of view. I am hoping that by sharing it you will point out to me what I'm missing. The main problems are IMO:

- The result of the query `{ collection: "users", doc: props.userId }` is mapped to props with `state.firestore.data.users[props.userId]` yet the resulting data is still an object where the key is the userId and the data is the value (`UserProfileInKeyValue`)
- The children will need a reference to the UserProfile document id to trigger any actions related to it. So in order to pass it down I'm merging the document id with the data (`UserProfileWithDocumentId`).
- The whole path from document query to props seems much to verbose

```ts
import * as React from "react";
import { compose } from "redux";
import { connect } from "react-redux";
import { firestoreConnect, isEmpty, isLoaded } from "react-redux-firebase";
import { UserProfile } from "types";
import { keys, first } from "lodash";

interface UserProfileWithDocumentId extends UserProfile {
  id: string;
}

interface UserProfileInKeyValue {
  [id: string]: UserProfile;
}

interface FetchUserProfileProps {
  userId: string;
  userData: UserProfileInKeyValue | null;
  children: (userData: UserProfileWithDocumentId) => React.ReactElement<any>;
}

export class FetchUserProfile extends React.Component<
  FetchUserProfileProps,
  {}
> {
  public render() {
    const { userData, children } = this.props;

    if (!isLoaded(userData)) {
      return null;
    }

    if (isEmpty(userData)) {
      return null;
    }
   
    console.log("userData", userData);
    const documentId = first(keys(userData))!;
    const documentData = userData![documentId] as UserProfile;
    return children({ id: documentId, ...documentData });
  }
}

interface PropsFromState {
  userData: UserProfileInKeyValue;
}

export default compose(
  firestoreConnect((props: FetchUserProfileProps) => [
    {
      collection: "users",
      doc: props.userId,
    },
  ]),
  connect<PropsFromState, {}, void>((state: any, props: any) => ({
    userData:
      state.firestore.data.users && state.firestore.data.users[props.userId],
  }))
)(FetchUserProfile) as any;
```

All in all this code is *very* complicated and verbose for trying to achieve something quite simpel. I really think there should be an easy declarative way to just fetch a document and pass it on to a child component. I might have missed it, but I went through the docs multiple times and can't find any example of this, or even the mention of the "doc" property in a query object. 

And overall I think it would really help if document data + ids are kept separate in a document model like Firestore has `doc = { id, data}`. That way you could just pass on data and use the same type models as you would use for the backend / database. For example my `UserProfile` model describes the stored profile data. It doesn't have an id field because that is not what is stored in the database document. The type is imported from the backend code, yet it can't be used conveniently, because react-redux-firebase will (when sorting data) inject the document id into the data. Maybe this made sense for the Firebase Realtime DB, and it is because of that legacy that things are the way they are, but for Firestore it just feels wrong for me.

Maybe I'm missing a few important concepts, so please enlighten me. Otherwise I will move on to some other / simpeler solution, because at this point I feel the library is getting more in my way than solving things.

**Comment by prescottprue** [comment]
@0x80 Have you tried [`storeAs`](http://react-redux-firebase.com/docs/firestore.html#storeAs) ? It addresses the "The whole path from document query to props seems much to verbose" concern by allowing you to store the result of your query wherever you want within redux state:

```js
const storeAsPath = 'currentUser'

compose(
  firestoreConnect(props => [
    {
      collection: 'users',
      doc: props.userId
      storeAs: storeAsPath
    }
  ]),
  connect(({ firestore: { data } }, props) => ({
    // use storeAs path to gather from redux
    userData: data[storeAsPath] && { data: data[storeAsPath], id: props.userId }
  }))
)
```

It is pretty common to already have the id of the document you are getting, which is why it isn't on the data object. That said, if getting data from `state.ordered` it would be nice to have the option to leave data under the data parameter (i.e. `{ id, data }`) instead of spreading it (what happens currently). This could be exposed through a config option, maybe something like `spreadOrderedData: false`?

@0x80 You are right about the pattern being legacy to match Real Time Database (it also made the transition much easier for many to make). After working with it for a bit, I realized that there are multiple reasons that things should stored differently (including subcollection support issues such as [#49 of redux-firestore](https://github.com/prescottprue/redux-firestore/issues)).

A different state layout would be a breaking change, but it is required at this point so I am definitely on board. Did you have a syntax in mind for how you want to be grabbing from redux state?


Also - while on the topic of breaking changes to make things work nicer, I have long since had an idea for an HOC (I have called `withPropsFromFirebase`) which sends data from Firebase listeners directly to props (not through redux first, or maybe optional). It seems like what you are mentioning is a perfect use case for something like that, maybe it would something like: 

```js
// NOTE: THIS IS NOT REAL - JUST AN EXAMPLE OF POSSIBLE FUTURE SYNTAX
withPropsFromFirebase((props) => [
  {
    collection: "users",
    doc: props.userId,
    propName: 'userData'
  },
])(({ userData }) => (

))

const SomeComponent = () => (
  <div>
    d
  </div>
)
```

**Comment by 0x80** [comment]
Hi @prescottprue

I had used storeAs before but this is a project I am only working on once in a while and it's been a few months since I touched it, so it slipped my mind. The current state of the docs really don't help in this regard, but you are already aware of that.

In my case I don't have the profile data upfront. The admin cycles a list of "pending user registrations" which are referring to user profiles by id. I'm only fetching the profile data once a registration document is selected.

The new `withPropsFromFirebase` syntax would definitely be a perfect fit for that, since I really don't need this data to be in redux state. Not having to select it from state is a definite win.

Good to hear that you're planning to tackle the document data structure. I don't have a specific syntax in mind, but I would keep all document entities in a `{id, data}` structure, to match the Firestore model. You could also add other things like 'ref/path' if that seems useful, but just having `id` and `data` as separate fields feels like the most sensible format to me.

I think the auto loading options could be nice, but really not essential. I would much rather have an `isLoading` prop injected onto the props, because it makes the client code cleaner and more readable. Having to import and call the `isLoaded` function really clutters things IMO.

Personally I wouldn't worry about breaking changes too much. I see Firestore clearly as a replacement for the Realtime DB (which was never designed to be a database to start with). So if you can afford it for your own use-cases I would even drop support for that RTDB all-together. I would rather focus my time and energy on things that will stay relevant in the near future.  

If you are up for it I would definitely recommend writing v3 in Typescript. It forces you to write cleaner code and documents everything nicely. I found the transition to be quite smooth, and it catches pretty much all the stupid mistakes I make. The tooling is solid and it doesn't get in the way for me.
Especially in combination with VSCode I really enjoy my coding life much more now 😄

**Comment by prescottprue** [comment]
Totally agree with the switch to Firestore, and have always known the transition off of RTDB was coming (since as you mentioned it wasn't really built to be a DB from the start).

At work we have started to transition over to Firestore and have built new features using it, but some of our main systems still use it.

As for typescript - I agree that it helps, and I have started using it for some projects. My main issue with it is that it makes the source harder to approach for vanilla js developers or those new to typescript. All of that said - I'll look back into tooling especially since Firebase's libraries are now written using it. ]

Either way, I really love discussions like this and have been looking for people trying to discuss features/syntax for v3. Feel free to open a PR to show how the transition may look or reach out over [gitter with some examples](http://gitter.im/redux-firebase/Lobby).

**Comment by prescottprue** [comment]
Side note: #368 Has has some discussion of `v3` features as well

**Comment by 0x80** [comment]
👍 Cool. I'm happy to help or discuss things. Unfortunately at the moment I am not in a position to spend time on PRs. Hopefully after April things will improve, but I do not know yet.

I can't speak for other developers of course, but I would be much more willing to help out on a project if the code is clearly written. Even if I didn't know Typescript, I think the inherit source documentation would help a lot in getting to know a foreign codebase. The current v2 source in that sense is really not very inviting to me. I haven't had a look at v3 yet though...

**Comment by 0x80** [comment]
@prescottprue thanks for the heads-up about this bug. Using `storeAs` seemed to have solved weird behaviour that I was seeing in my app. 

I cleaned up my code according your suggestions. The mapping at the bottom is a bit different since `data[storeAsPath]` contains an object with a the data on the id key.

```ts
import * as React from "react";
import { compose } from "redux";
import { connect } from "react-redux";
import { firestoreConnect } from "react-redux-firebase";
import { UserProfile, Document } from "backend-types";

interface FetchUserProfileProps {
  userId: string;
  userData: Document<UserProfile> | null;
  children: (userData: Document<UserProfile>) => React.ReactElement<any>;
}

export class FetchUserProfile extends React.Component<
  FetchUserProfileProps,
  {}
> {
  public render() {
    const { userData, children } = this.props;

    if (!userData) {
      return null;
    }

    console.log("userData", userData);
    return children(userData);
  }
}

const storeAsPath = "selectedUserProfile";
export default compose(
  firestoreConnect((props: FetchUserProfileProps) => [
    {
      collection: "users",
      doc: props.userId,
      storeAs: storeAsPath,
    },
  ]),
  // @ts-ignore
  connect(({ firestore: { data } }, props: FetchUserProfileProps) => ({
    userData: data[storeAsPath] && {
      data: data[storeAsPath][props.userId],
      id: props.userId,
    },
  }))
)(FetchUserProfile) as any;
```

**Comment by prescottprue** [comment]
@0x80 I started to try to play with some stuff on [the typescript branch](https://github.com/prescottprue/react-redux-firebase/tree/typescript), but haven't had enough time to get very far.

Really interested in giving this a go for v3.0.0, but things are already so busy that it may take a while to make time to learn typescript before features are needed.

**Comment by prescottprue** [comment]
Going to close in favor of #368.
