### ISSUE TITLE
Demo broken, nothing happens, no console or websocket traffic

### ISSUE THREAD

**Issue by ElijahLynn** [prescottprue/react-redux-firebase#433]
Went to https://demo.react-redux-firebase.com/ but no todo can be added, I enter text and nothing happens, no console or websocket traffic.

**Comment by prescottprue** [comment]
@ElijahLynn It seems like am seeing things show up just fine? The list places your newest todo at the bottom (this may not be what you were expecting):
![todoworking](https://user-images.githubusercontent.com/2992224/37873460-3661bbb6-2fd2-11e8-8fd9-182b7e8c0b0d.gif)

As for the traffic, it appears that in the picture you provided, the todos query is appearing (seen in the data field of the top most visible frame):


Am I misunderstanding? Do you think that it would be more clear if the list was reversed (i.e. newest first instead of last)?

**Comment by ElijahLynn** [comment]
It wasn't appearing at the bottom when I tried it, it is now though, I think there is a bug somewhere with state somehow. But we can leave closed for now since I can't reproduce and it does appear to be working.

It would be an improvement to have new items added to the top, and also if the "enter/return" key can also submit the item, in addition to the "+".
