### ISSUE TITLE
credentials token is not a valid token

### ISSUE THREAD

**Issue by Fandekasp** [prescottprue/react-redux-firebase#511]
**Do you want to request a *feature* or report a *bug*?**  

(If this is a *usage question*, please **do not post it here**—post it on [gitter](https://gitter.im/redux-firebase/Lobby). If this is not a “feature” or a “bug”, or the phrase “How do I...?” applies, then it's probably a usage question.)
Bug

**What is the current behavior?**
When login, profile, user and credential are sent back. `credential.idToken` cannot be used as auth header to a backend api server, raising a verify_id_token ValueError.
By debugging randomly, I found out that `user._lat` on the other side is a valid token that can successfully be used as authentication header. No idea what `_lat` is supposed to mean.

**What is the expected behavior?**
`credential.idToken` should be a valid token.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
 redux@4.0.0, react-redux@5.0.7, react-redux-firebase@2.1.6

**Comment by prescottprue** [comment]
I believe you are supposed to use [`currentUser.getIdToken` to get a token as mentioned in the Firebase docs](https://firebase.google.com/docs/auth/admin/verify-id-tokens#retrieve_id_tokens_on_clients).

Not exactly sure why the send back that token, but there is refreshing that the Firebase JS SDK handles automatically. Reach out if that doesn't work as you expect.

**Comment by prescottprue** [comment]
Closing since I believe the wrong token was being used. In most examples of talking with a backend, the `getIdToken` is used since then the backend can use `firebase-admin`'s `verifyIdToken` to verify.

Realized it is also what they do in the [authorized-https-endpoint function sample](https://github.com/firebase/functions-samples/tree/Node-8/authorized-https-endpoint). There example does it using an express middleware, which I find pretty clean, and works great in most cases.

Reach out if this isn't what you were looking for.
