### ISSUE TITLE
Logout raises error when firebase rules require auth != null access.

### ISSUE THREAD

**Issue by Lecss** [prescottprue/react-redux-firebase#529]
**What is the current behavior?**
Logout raises error when firebase rules allow only authenticated user access. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

currently using the following firebase rules: 
  ```
 {
     "rules": {
       "users": {
         "$uid": {
             ".read": "auth != null && auth.uid == $uid",
         }
   }
```

On logout, I get the following error:
Error with profile listener: Database: Client doesn't have permission to access the desired data. (database/permission-denied). Error: Database: Client doesn't have permission to access the desired data. (database/permission-denied).

**What is the expected behavior?**

Logout functionality should not raise errors. 

Looks this is due to the fact that in actions/auth.js , authUid is set to null before unwatching user profile. Changing the order of this solves the issue. Happy to raise a PR for this if this is confirmed as the right solution. 
    
    firebase._.authUid = null;
    unWatchUserProfile(firebase);

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

I see this behaviour in react-native, but seems to be generic one rather than react-native specific.

**Comment by prescottprue** [comment]
Which version are you using? Have you tried installing from the `@next` tag?

These logs are just warnings that Firebase produces to let you know that listeners are still attached. In the case of the profile listener, the issue [was reported before](https://github.com/prescottprue/react-redux-firebase/issues/494) and was fixed [in this merge](https://github.com/prescottprue/react-redux-firebase/pull/516) as part of the [`v2.2.0-alpha` release](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.2.0-alpha).

This is currently on an upcoming feature since the logs are just warnings, but since it is being reported so often, I might get it out to `@latest` a bit faster. Thanks for reaching out!

**Comment by prescottprue** [comment]
Going to close since this has been inactive for a while. `v2.*.*` has also been out for a while.

If anyone is still seeing this, feel free to reference this in a new issue.
