### ISSUE TITLE
bug(reducers): different firestore queries at the same path run over state

### ISSUE THREAD

**Issue by dantman** [prescottprue/react-redux-firebase#548]
**Do you want to request a *feature* or report a *bug*?**  

Bug.

**What is the current behavior?**

If I decorate a component with the following and mount it:
```js
@firestoreConnect(props => [
	{collection: 'food'},
])
@connect(state => ({
	food: state.firestore.ordered.food,
}))
```

Then I mount a different component decorated with the following:
```js
@firestoreConnect(props => [
	{
		collection: 'food',
		where: ['type', '==', 'fruit'],
		orderBy: ['name'],
	},
])
@connect(state => ({
	fruit: state.firestore.ordered.food,
}))
```

I notice that the first component is then updated with the same list of items. i.e. If you mount a list of all food items, then mount a component that filters the fruit items, then the list of all food items (that does not contain a filter) is updated to only list fruit items.

This effect also appears to occur with the `doc: ` format of query.

**What is the expected behavior?**

One would think that different instances of firestoreConnect that have different queries for a collection would keep track of data separately. Instead it appears as if there is only one list of documents per collection and when you mount a new component with a different query it updates the list for all users of that collection with the other query.

If you happen to use this in an app where you have a stack of screens and tapping on an item in a list opens a screen that uses `doc` to display data for a single item. Then this makes it so that after tapping the list to view a single item and pressing back to return to the list, the list now only contains the item you tapped instead of all the items it was displaying.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

```
* `react-redux-firebase@2.1.8`
* `redux-firestore@0.5.8`
* `react-native-firebase@5.0.0`
* `react@16.5.0`
* `react-native@0.57.1`
```

**Comment by prescottprue** [comment]
Thanks for reporting

### Current Workaround
If you use `storeAs` then your queries will be stored separately in state - that way only updates for that specific query will update that part of state.

### Longer Term
In [the v1.0.0-* version series (still under `@alpha` tag) of redux-firestore](https://github.com/prescottprue/redux-firestore/wiki/v1.0.0-Roadmap) data is stored by query name instead of collection name. This was to address issues with subcollections stored on collection docs, but it should also be able to address this issue.

If it doesn't currently store these two queries separately, we should get that in as a feature while it is still in alpha!

**Comment by prescottprue** [comment]
@dantman Let know if you get a chance to checkout `v1.0.0-alpha`

**Comment by prescottprue** [comment]
Closing since this is in `redux-firestore` and I believe it is solved in newer versions. If that is not the case, feel free to open an issue on that repo. Thanks for reporting!
