### ISSUE TITLE
Dealing with route changes

### ISSUE THREAD

**Issue by DeividasK** [prescottprue/react-redux-firebase#55]
The problem I have right now is that on route change, the data lags with updates.

For example, at one page I show `goals` of a specific user. On another page I show `goals` of all users. When the route chagnes, the goals and the state update after a small time interval (~100-500ms) and this does not look pretty.

Is there a way to maybe:
- delete the data on component unmount?
- do not mount the component until firebase syncs data?

Any suggestions would be highly appreciated :)

**Comment by prescottprue** [comment]
Can you possibly show some of the syntax of how you are calling the route change?


Not mounting the component until the firebase data is synced might be a possibility depending on where you call the route change.

**Comment by DeividasK** [comment]
Here's my routes.
```js
<Router history={ history }>
  <Route path='/' component={ MainContainer }>
    <Route path='tutorial' component={ TutorialWrapper }>
      <IndexRoute component={ Introduction } />
      <Route path='step-1' component={ Step1 } />
      <Route path='step-2' component={ Step2 } />
      <Route path='step-3' component={ Step3 } />
      ...
    </Route>
  </Route>
</Router>
```

User navigates those routes using `react-router`s `Link` function, e.g.
```js
<Link to={ link }>Go to some route</Link>
```

**Comment by prescottprue** [comment]
@DeividasK It seems like you could pretty easily make a HOC wrapper that requires some data using [redux-auth-wrapper](https://github.com/mjrussell/redux-auth-wrapper).

The plan is to include a function for creating these types of wrappers in future versions, but I will try to come up with a nicer solution in the short term.

**Comment by prescottprue** [comment]
Pointing the queries to two different places (using `storeAs`) should work.

The issue lies in the fact that the data already exists in that location within redux, and your query is just updating that location. `isLoaded` will return true before the new data has loaded because data at that location in redux (which is passed to a component prop using `connect`) already exists from the last query. Using `storeAs` will place the data in different locations within redux, so `isLoaded` will work as expected.

To your point though: I like the idea of offering "empty on unmount" capability for queries/data loaded from within a component. It will take a little research to determine scope of this, but after that it may be added to the roadmap.

**Comment by prescottprue** [comment]
"empty on unmount" capability is under consideration, and will most likely be part of v2. Using `storeAs` is the current suggestion.
