### ISSUE TITLE
question(query): using populate in redux thunk

### ISSUE THREAD

**Issue by alexpchin** [prescottprue/react-redux-firebase#571]
A question here... 

I'm looking to populate a firestore query in a thunk so that I can decouple the query logic away from the firestoreConnect / connect functions into it redux modules. Several reasons, but one might be if we change away from firebase? However, I'm struggling...

I can pass `getFirestore` through to my `thunk` and gain access to `firestore`. However, I'm struggling in the documentation to find whether I can use populate here?

```js
export const photosIndex = () => {
  return async (dispatch, getState, { getFirebase, getFirestore }) => {
    try {
      const firestore = getFirestore();

      const populates = [{ child: "user", root: "users", keyProp: "id" }];

      const querySnapshot = await firestore.get({
        collection: "photos",
        populates
      });

      // Initialise a new array
      const photos = [];

      if (querySnapshot.empty) {
        console.log("No documents found");
      } else {
        querySnapshot.forEach(doc => {
          const data = doc.data();
          photos.push(data);
        });
      }

      dispatch(setPhotosFetchSuccess(photos));
    } catch (e) {
      console.log("Error fetching photos", e);
    }
  };
};
```

Any ideas or thoughts would be much appreciated.

**Comment by alexpchin** [comment]
I've also been trying to put `populate` in a reducer to try to populate there before `mapStateToProps`? But I can't seem to get that to work either...

```js
let photos = populate(state.firestore, "photos", populates); 
```

**Comment by alexpchin** [comment]
I think basically, an example with a `get()` in a Thunk and also a `get` with a populate in a Thunk would be really useful in the docs.

**Comment by prescottprue** [comment]
@alexpchin Population with firestore was just recently added, and it was setup to work [with `setListener` and `setListeners` ](https://github.com/prescottprue/redux-firestore/blob/alpha/src/actions/firestore.js#L203) which are used by `firestoreConnect`. Since you are just using get here it won't run the other queries necessary for population  - that said, the plan is to add populate to get as well.

As for "decoupling the query logic" [the v1.0.0 roadmap](https://github.com/prescottprue/redux-firestore/wiki/v1.0.0-Roadmap) discusses the current plans for trying to address [reusing query config in HOCs](https://github.com/prescottprue/redux-firestore/wiki/v1.0.0-Roadmap#pattern-query-config-as-a-function) - Hoping this would help address some concerns since even when moving to "another system other than firebase" these queries could then just be passed differently or with some formatting function.

Would love to continuing to keep an open discussion on this even after adding `populate` to `get`. Thanks for reaching out!

**Comment by alexpchin** [comment]
Just for people who are curious before populate is added to `.get`:

```
export const photosIndex = querySnapshot => {
  return async (dispatch, getState, { getFirebase, getFirestore }) => {
    dispatch(photosFetchStart());
    try {
      const firestore = getFirestore();

      const querySnapshot = await firestore.get({ collection: "photos" });

      const data = [];

      querySnapshot.forEach(doc => {
        // Fetch the data from the document
        const docData = doc.data();

        // Add the id key
        docData.id = doc.id;

        data.push(docData);
      });

      // Can't be inside the forEach
      for (photo of data) {
        // Populate with user data
        if (photo && photo.user) {
          const userData = await firestore.get({
            collection: "users",
            doc: photo.user
          });

          // Fetch the data from the document
          photo.user = userData.data();

          if (photo.user) {
            // Add the id key
            photo.user.id = userData.id;
          }
        }
      }

      dispatch(photosFetchSuccess(data));
    } catch (error) {
      dispatch(photosFetchFail(error));
    }
  };
};
```

**Comment by prescottprue** [comment]
Going to track in [the redux-firestore ticket](https://github.com/prescottprue/redux-firestore/issues/155)
