### ISSUE TITLE
getState() with thunk returns firebase as a map

### ISSUE THREAD

**Issue by brianlovin** [prescottprue/react-redux-firebase#59]
Hey there – I'm trying to use the firebase.profile from redux in order to construct some queries to firebase, based on the user's uid. I'm having trouble accomplishing this in my action. Here's what I'm running:

```
export const foo = () => (dispatch, getState, getFirebase) => {
  const firebase = getFirebase()
  const state = getState()

  console.log(firebase, state)
  ...
}
```

And `state` in this case returns:
<img width="234" alt="screen shot 2017-02-05 at 6 51 26 pm" src="https://cloud.githubusercontent.com/assets/1923260/22633232/6d373ad2-ebd4-11e6-98df-4a94d4b4fc26.png">

Which means I can't access my profile stored in firebase.profile.

It's odd because in my redux store I can see all of this information:
<img width="697" alt="screen shot 2017-02-05 at 6 54 13 pm" src="https://cloud.githubusercontent.com/assets/1923260/22633253/89e8266e-ebd4-11e6-944b-9d006591e7bb.png">

Does this look familiar at all?

**Comment by prescottprue** [comment]
This is the intended functionality. The data within `state.firebase` is an immutable Map. In order to get data from a data path use `dataToJS()`. For things at the top level such as auth and profile use `pathToJS()`.

**Note:** redux-devtools displays Maps as objects (which is why you are seeing the data)

An action can use uid like so:
```js
export const foo = () => (dispatch, getState, getFirebase) => {
  const firebase = getFirebase()
  const { uid } = pathToJS(firebase, 'auth')
  firebase.push(`some/${uid}`, { some: 'val' })
}
```

**Comment by brianlovin** [comment]
Hm, still having trouble accessing the profile info itself. My action is now:

```
export const setStories = (frequency) => (dispatch, getState, getFirebase) => {
  const firebase = getFirebase()
  
  const userData = dataToJS(firebase, 'profile')
  const userPath = pathToJS(firebase, 'profile')
  console.log('user data is: ', userData)
  console.log('user path is: ', userPath)
}
```

And I see this in the console:

<img width="476" alt="screen shot 2017-02-05 at 8 33 47 pm" src="https://cloud.githubusercontent.com/assets/1923260/22634786/7daa01b6-ebe2-11e6-86be-9a93769e3570.png">
<img width="499" alt="screen shot 2017-02-05 at 8 33 54 pm" src="https://cloud.githubusercontent.com/assets/1923260/22634788/8019b52c-ebe2-11e6-9c7b-76cd1ec72fe6.png">

**Comment by prescottprue** [comment]
Make sure to use `getState().firebase` instead of `getFirebase()` like so:

```js
export const setStories = (frequency) => (dispatch, getState, getFirebase) => {
  const firebase = getFirebase()
  const userPath = pathToJS(getState().firebase, 'profile')
  console.log('user path is: ', userPath)
}
```

**Comment by brianlovin** [comment]
Sorry for the troubles here, this is still returning undefined.

Code:

```
export const setStories = (frequency) => (dispatch, getState, getFirebase) => {
  const firebase = getFirebase()
  const state = getState()
  const userPath = pathToJS(state.firebase, 'profile')
  console.log('fb is: ', firebase)
  console.log('state is: ', state)
  console.log('user path is: ', userPath)
}
```

output:

<img width="743" alt="screen shot 2017-02-05 at 8 47 47 pm" src="https://cloud.githubusercontent.com/assets/1923260/22635019/6bdb0816-ebe4-11e6-9925-080d671aa876.png">

**Comment by prescottprue** [comment]
Have you imported `pathToJS`? Can you share a whole repository or at least a complete snippet with imports?

It would also be nice to include the component where you are dispatching the action.

**Comment by brianlovin** [comment]
Wow. It's because I was dispatching from a componentDidMount() using `nextProps.dispatch`. Changing to `this.props.dispatch` seems to have cleared it up – thanks so much for your quick replies here Scott, really appreciate that!

**Comment by piya23300** [comment]
@brianlovin I have the same you.
Can you show the code example to solve it?

**Comment by prescottprue** [comment]
@piya23300 I don't believe what you are seeing is related to this issue.

In your example, quizzes will be undefined unless that data is first loaded into redux (`dataToJS` just gets it out of redux)

If you are trying to load data, you should look into [`firebaseConnect`](http://react-redux-firebase.com/docs/queries.html#queries). It is the common pattern for loading data, since it attaches/detaches approaiate listeners when components are mounted/unmounted. [This is how data is loaded in the material example including loading todos](https://github.com/prescottprue/react-redux-firebase/blob/master/examples/complete/material/src/routes/Home/containers/HomeContainer.js#L26-L40).

Also, [the projects route is an example of using populate](https://github.com/prescottprue/react-redux-firebase/blob/master/examples/complete/material/src/routes/Projects/containers/ProjectsContainer.js#L22-L31) if you are interested in that.

If you believe you are still having problems, feel free to open up an issue or hop on [gitter](https://gitter.im/redux-firebase/Lobby) with your questions.

**Comment by piya23300** [comment]
@prescottprue Thank you. I followed your example. It does not work because I forgot to change database roles at Firebase.

I have to enable `enableLogging: true` so I will see why the data is null ^^.
Thank you so much.
