### ISSUE TITLE
react-redux-firebase vs redux-react-firebase

### ISSUE THREAD

**Issue by moroshko** [prescottprue/react-redux-firebase#6]
@prescottprue I see that you are one of the contributors to [`redux-react-firebase`](https://github.com/tiberiuc/redux-react-firebase). 

Could you provide some insights to the differences between `react-redux-firebase` and `redux-react-firebase`? They look very similar, and this is very confusing 😕

**Comment by prescottprue** [comment]
@moroshko They were originally actually the same library, but redux-react-firebase was left unattended for a few months when there were crucial Pull Requests. Now it differs by including features that were requested by a few of us that needed access to Firebase's `once` and utilities like population and deboucing.

#### Main differences now:
* [population functionality](https://prescottprue.gitbooks.io/react-redux-firebase/content/populate.html) similar to mongodb's
* [access to firebase's `storage`](https://prescottprue.gitbooks.io/react-redux-firebase/content/storage.html)
* `uniqueSet` method helper for only setting if location doesn't already exist

#### Well why not combine?
I am in the process of writing up an article comparing the two, including the difference in defaults/utils. I have also been talking to the author of redux-react-firebase about combining, but we are not sure that the users of both want that at this point. Join us on [the redux-firebase gitter](https://gitter.im/redux-firebase/Lobby) if you haven't already since a ton of this type of discussion goes on there.

**Comment by prescottprue** [comment]
@moroshko I added an FAQ section as part of the [v1.0.2 release](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.0.2) that explains this. Hope it helps others that are wondering the same thing.

**Comment by moroshko** [comment]
@prescottprue Thanks a lot for clarifying this!
