### ISSUE TITLE
feat(core): decrease bundle size

### ISSUE THREAD

**Issue by idanlo** [prescottprue/react-redux-firebase#624]
![image](https://user-images.githubusercontent.com/28350511/52150813-c6387d80-2679-11e9-823c-e21d0ecdbc3f.png)

**Comment by prescottprue** [comment]
@idanlo What is your build setup (i.e. webpack, rollup?) Also what version or whichever tool? It seems like this screenshot is showing how big the bundle itself is (guessing the UMD bundle?), but if you are using a new version of webpack, you should be loading the Commonjs build and have treeshaking take care of removing any code you aren't using.

**Comment by idanlo** [comment]
using create-react-app

**Comment by prescottprue** [comment]
@idanlo create-react-app uses react-scripts to contain all of the build settings. Which version of react-scripts are you running? Also which tool are you using to check bundle size?

**Comment by prescottprue** [comment]
@idanlo I am thinking that changing the top level export structure may be one way to combat this, definitely large.

Also having folks import like `import firebaseReducer from 'react-redux-firebase/firebaseReducer'` would help, but not sure everything is setup to do that correctly for all the versions.

Open to any changes you have in mind regardless of how drastic. Thanks for reaching out!

**Comment by prescottprue** [comment]
I was able to confirm that pulling things in directly from the `lib` folder helps, so I will most likley be changing the docs to use this pattern instead:

```js
import firebase from 'react-redux-firebase/lib/reducer'
import firestore from 'redux-firestore/lib/reducers'
```

And import cost also verifies:

![image](https://user-images.githubusercontent.com/2992224/53597041-03e3d580-3b56-11e9-902b-5ed14df03fee.png)

That said, I would still like to aim to make things much smaller than that. Thinking that the `lib` version should be minified and have source maps if if it is still following the folder structure of `src`.

It is great that you brought this up because the plan was to have this be the new pattern for imports in newer versions anyway, so changing to this in the docs of the current version will be a nice transition. Thanks for reaching out!

**Comment by prescottprue** [comment]
v3 sizes are below the 100kb mark. Going to continue to try to drop this further - currently experimenting with [switching redux-firestore to Typescript](https://github.com/prescottprue/redux-firestore/pull/238) which may help a bit as well
