### ISSUE TITLE
bug: my firebaseConnect() higher order component not working

### ISSUE THREAD

**Issue by wizzywit** [prescottprue/react-redux-firebase#647]
Good day developers I am still new to React.JS and i have been working with react, redux and firebase and my firebase is well configured and connected to my react app as it submits the data from the form to the database but on working on my dashboard using the compose to combine different HOC to one so i could display that data i get this error messages on console:

index.js:1446 Warning: Failed context type: The context store is marked as required in FirestoreConnect(Dashboard), but its value is undefined.

Uncaught Error: Context from react-redux not found. If you are using react-redux v6 a v3.. version of react-redux-firebase is required. Please checkout the v3 migration guide:

The above error occurred in the <FirestoreConnect(Dashboard)> component:

below is my Dashboard.js component
https://github.com/wizzywit/mario/blob/0a65061dab783ae1a930e7cf3251f546010736a6/src/component/dashboard/Dashboard.js#L1-L47
 
This is my Config file
https://github.com/wizzywit/mario/blob/0a65061dab783ae1a930e7cf3251f546010736a6/src/config/fbConfig.js#L1-L16

and my rootReducer file
https://github.com/wizzywit/mario/blob/0a65061dab783ae1a930e7cf3251f546010736a6/src/store/reducers/rootReducer.js#L1-L13

**Comment by prescottprue** [comment]
@wizzywit As stated in the error, if you are using react-redux v6 ([which you appear to be](https://github.com/wizzywit/mario/blob/0a65061dab783ae1a930e7cf3251f546010736a6/package.json#L9)), you must upgrade to react-redux-firebase v3. The [install section also mentions how to install the v3 version from the `next` tag](https://github.com/prescottprue/react-redux-firebase#installation) - but since it is still not stable, you may instead want to downgrade to `react-redux@^5`.

**Comment by harvey56** [comment]
@prescottprue upgrading to the `next` version generates a new error : `Object(...) not found` at this line in your store : `reactReduxFirebase(firebase, config)`

**Comment by prescottprue** [comment]
@harvey56 reactReduxFirebase is not part of the v3 api currently [as mentioned in the v3 migration guide](http://docs.react-redux-firebase.com/history/v3.0.0/docs/v3-migration-guide.html).

That said, a number of folks have been asking to still have access to `store.firebase` which is what the `reactReduxFirebase` store enhancer does, so it may end up being added back to the api for v3. Again though, it isn't currently part of the new api, so that is why you would be seeing the error.
