### ISSUE TITLE
Query field in specific subcollection

### ISSUE THREAD

**Issue by GitHubGreg** [prescottprue/react-redux-firebase#658]
Sorry if this is not a bug, but I am trying to return only `private` images inside the `images` subcollection of a `user` using a where clause. 

```
const query = profileUserId => {
  return [
    {
      collection: 'users',
      doc: profileUserId,
      subcollections: [
        { collection: 'images', where: ['labelValue', '==', 'private'] }
      ],
      orderBy: ['createdAt', 'desc'],
      storeAs: `userProfileImages`
    }
  ];
};
```

My understanding was that querying across multiple subcollections isn't possible, but within a given subcollection it is.

But the above is not working. If I remove the where clause it works and returns all the image documents.

**Comment by prescottprue** [comment]
@GitHubGreg Did you check to see if errors were being dispatched and writing into redux? This sometimes happens when folks have not setup indexes in Firestore.

**Comment by GitHubGreg** [comment]
Thanks for the reply. Good question. I would gave expected that since it is a new query, but no firebase 'create index' message was returned. 

Good point re. the id. I also tried with a known profile id assigned directly without success. But the id field works dynamically too since the query works when I remove the where clause.

**Comment by prescottprue** [comment]
So you did try the other query I show above? With the query parameters at the sub-collection level?

**Comment by GitHubGreg** [comment]
Yes, I did try that but it still fails to return anything. Only when I remove the where clause does it work. I have verified that the images do indeed have `labelValue` set to 'private'.

**Comment by illuminist** [comment]
Firebase dispatched error doesn't state that the query is lack of index, just plain 
```
{
  type: '@@reduxFirestore/LISTENER_ERROR',
  payload: {
    code: 'failed-precondition',
    name: 'FirebaseError'
  },
  ...otherMeta
}
```
which isn't meaningful. But firebase will usually logs into a console that something is wrong, in this case might be
```
FirebaseError: The query requires an index. You can create it here: <URL link to create a proper index>
```
which indicates that the query doesn't have an index to use.

The `orderBy` query should be in the subcollection as it should do ordering within subcollection, while the parent collection already has already specify doc so it cannot be ordered as it would try to sort by `users.$.createdBy` instead of `users.<userId>.images.$.createdBy`.

**Comment by prescottprue** [comment]
@illuminist @GitHubGreg  Did either of you try providing `logListenerError` true to get the listener error? That should make it so that the error is logged to the console.

Made [this new issue in redux-firestore to track passing that message to the action dispatch](https://github.com/prescottprue/redux-firestore/issues/207).

Going to close since it appears this was due to the index error message not being passed along. If there is an example to repro an issue outside of the index error, feel free to post and I can reopen.
