### ISSUE TITLE
Can't import ReactReduxFirebaseProvider

### ISSUE THREAD

**Issue by PeterPil** [prescottprue/react-redux-firebase#662]
I want add a firebase to project, but i can't import ReactReduxFirebaseProvider, only have an error: "Cannot resolve symbol 'ReactReduxFirebaseProvider'".
 I use the latest version of all libs:
"react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-redux": "^6.0.1",
    "react-redux-firebase": "^2.2.6",
    "redux-firestore": "^0.7.2"

**Comment by prescottprue** [comment]
`ReactReduxFirebaseProvider` is only available in `v3.0.0` versions of `react-redux-firebase` as showing in [the v3 migration guide](http://docs.react-redux-firebase.com/history/v3.0.0/docs/v3-migration-guide.html). Since you are still using v2, you will want to follow the [main instructions in the README](https://github.com/prescottprue/react-redux-firebase#use).

**Comment by PeterPil** [comment]
Thanks for the issue, it's all okay. I missed it.
