### ISSUE TITLE
Trying use getFirebase, but catch an error

### ISSUE THREAD

**Issue by PeterPil** [prescottprue/react-redux-firebase#663]
I use the newest version of react-redux-firebase: "^3.0.0-alpha.10" and react-firestore: "1.0.0-alpha.2" and want use getFirebase, but i can't use it, because get an error: "getFirebase is not a function". I found issue #620  but It useful for getFirestore. With getFirestore i have no problem.
![image](https://user-images.githubusercontent.com/42355415/55287897-fcfbed00-53b7-11e9-95ab-14b904c05d35.png)

In react-redux firebase modul i not found enhancer files, maybe in this problem

Help me to solve that, thanks

**Comment by prescottprue** [comment]
getFirebase it not part of the new v3 api due to how the new context setup works (using a provider). Not sure, but from the error you showed it appears that you won't need to use `getFirebase` if you use [`login`](http://react-redux-firebase.com/docs/auth.html#logincredentials) which supports email login and automatically dispatches auth actions.

**Comment by prescottprue** [comment]
This has been noted in the migration guide for v2 -> v3, so going to close
