### ISSUE TITLE
bug(profile): providerData is written as empty array in Firestore

### ISSUE THREAD

**Issue by harshithmullapudi** [prescottprue/react-redux-firebase#699]
It 's updating the profile in firestore with provider data as empty array and if we by default set profile how do we know that it's first login

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
react-redux-firebase : 3.0.0 - 11

**Comment by prescottprue** [comment]
You can provide `profileFactory` to change how profiles are written to Firestore (or Real Time Database if you are using that instead) as noted [in the profile recipes section of the docs](http://react-redux-firebase.com/docs/recipes/profile.html#change-how-profiles-are-stored).

That said, provider data should only be included if it isn't an empty array, so I'll switch the ticket to focus on that.

**Comment by prescottprue** [comment]
Fix released in [v2.3.0](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.3.0)

**Comment by tomoyuki28jp** [comment]
@prescottprue I setup my react-redux-firebase like this.
https://react-redux-firebase.com/docs/recipes/roles.html#automatically-assign-role-when-user-signs-up

providerData is stored in firestore as a empty array even when user.providerData is not empty.

(Is this because firestore does not support directly nested arrays? https://github.com/firebase/firebase-js-sdk/issues/193#issuecomment-457937610 )

**Comment by prescottprue** [comment]
@tomoyuki28jp Thanks for posting, the example should be updated - you may also want to stick to assigning roles in a cloud function since that makes it easier when it comes times to create security rules

**Comment by prescottprue** [comment]
Updated the docs to also include an example of doing this with a cloud function
