### ISSUE TITLE
Cannot read property "SDK_VERSION" of undefined

### ISSUE THREAD

**Issue by rmscoelho** [prescottprue/react-redux-firebase#706]
A member of the group I'm in is having this bug when she imports the library.

I installed it with yarn because anything else would basically make the project full of errors (I know this because one of the group members tried with another library)

Using Windows 10.
Also using redux-firestore, redux-thunk, axios-middleware.

![60598400_323037235058257_5596033797582749696_n](https://user-images.githubusercontent.com/50850007/58058435-e294f300-7b60-11e9-8501-a414fd38541d.png)

**Comment by prescottprue** [comment]
Seems like you are not passing a valid firebase instance into the library. It is hard to say for sure though without more context. Can you provide code that reproduces the bug so more investigation can be done?

Not sure what what exactly is being described with `I installed it with yarn because anything else would basically make the project full of errors (I know this because one of the group members tried with another library)` - the package installer you use shouldn't be causing errors within the code itself or something else is up (i.e. installing unintended versions because of no matching lock file or loose dependencies in `package.json`).

**Comment by rmscoelho** [comment]
I'll ask her what she did for this error to appear and post it here.

> Not sure what what exactly is being described with `I installed it with yarn because anything else would basically make the project full of errors (I know this because one of the group members tried with another library)` - the package installer you use shouldn't be causing errors within the code itself or something else is up (i.e. installing unintended versions because of no matching lock file or loose dependencies in `package.json`).

I meant using npm install. Sorry for not being clear enough.
And I have no idea why it happened, but it fucked the project and I had to give her an older version, and we didn't get anymore errors after installing stuff with yarn.

**Comment by rmscoelho** [comment]
![60467815_2200272043616823_3960587178425188352_n](https://user-images.githubusercontent.com/50850007/58088510-befe9680-7bba-11e9-93f5-25ee246a8455.png)

Here as promised.
We import reactReduxFirebase and getFirebase and then call the store and it gives that error.

Sorry for bothering you, and thanks in advance

**Comment by prescottprue** [comment]
@rmscoelho It appears that you aren't passing the Firebase instance to the store enhancer (`reactReduxFirebase`), it should be the first argument and config should be the second argument:

```js
const rrfConfig = {
  // userProfile: 'users' // store profile in "users" path of RTDB
}

reactReduxFirebase(RNFirebase, rrfConfig)
```

The error is happening because you aren't passing that instance (since it can not find SDK_VERSION parameter of the Firebase instance)
