### ISSUE TITLE
Calling firebase.updateProfile directly after firebase.login causes profile.isLoaded and profile.isEmpty incorrectly change values

### ISSUE THREAD

**Issue by mawilliamson** [prescottprue/react-redux-firebase#771]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
I am calling firebase.login(), then directly after, I am calling firebase.updateProfile(). firebase.updateProfile() is finishing before firebase.profile is loaded from the login. This causes firebase.profile to have the values that were updated with {..., isLoaded:true, isEmpty:false} values, even though all the profile values from login are not loaded.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

```
login = ({ firebase }) => async ({email, password}) => {
        await firebase.login({
          email,
          password
        });

        await firebase.updateProfile({
          phoneNumberConfirmed: false,
          updatedAt: firebase.firestore.FieldValue.serverTimestamp()
        });
};
```
**What is the expected behavior?**
I am expecting firebase.login() and firebase.updateProfile() to work with each other and only have {..., isLoaded:true, isEmpty:false} when firebase.profile is fully loaded from firebase.login()

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
v3.0

**Comment by prescottprue** [comment]
Thanks for reporting. Currently the profile listener is actually separate from login and is triggered by auth state change with the results write to redux state, so it may take a bit of a change to handle this case.

Something to consider may be using RTDB or Firestore to store profile values instead of storing it on the built in profile object. I say this for a few reasons:
* You can trigger events and watch for updates based on changes to profiles in a DB (to my knowledge there aren't listeners or cloud function events for auth profile changes).
* The client would only get updates to its profile after changing auth state. Meaning that calling [`updateUser`](https://firebase.google.com/docs/reference/admin/node/admin.auth.Auth.html#updateuser) in a cloud function would make client's data out of sync unless their auth is refreshed
* Updates to Firestore/RTDB profiles on login is built into react-redux-firebase, so passing `updatedAt` on login would just require an extra argument to `login`

**Comment by mawilliamson** [comment]
@prescottprue 

The method you described works for me!

Thank you so much!
