### ISSUE TITLE
Adding firebase parameter to profileFactory in createUserProfile

### ISSUE THREAD

**Issue by dannyvaughton** [prescottprue/react-redux-firebase#772]
I would like to discuss/request a small addition to the `profileFactory` callback in the `createUserProfile` user function.

Currently `createUserProfile` calls `config.profileFactory` with two parameters: `userData` & `profile`. I would like to discuss adding third: `firebase`.

The reason is because in profileFactory, I would like to run a few database checks before writing data to the user's profile. I am struggling with using firebase within this function because firebase & firestore have not yet been instantiated.

Currently, I am placing this logic within my Login & Sign Up components, but I feel it would be better placed in profileFactory.

What are your thoughts & would you like me to submit a PR?

**Comment by prescottprue** [comment]
Interesting idea! Feel free to submit a PR.

Have you been using the `next` version (v3 series in pre-release)? I ask because that is about to be released to latest, and since this is a change in the API, maybe it would be good to add it to a pre-release version before it goes to latest?

If not, making it the third argument should prevent breaking changes for most, so we could add it to a new minor version of the `2.*.*` versions (maybe 2.5.0).

Thanks for reaching out!

**Comment by dannyvaughton** [comment]
Yes, I am using v3. Ok great thanks, will submit a PR 👍

**Comment by prescottprue** [comment]
Released in v3.0.0-beta is is now part of `latest` since v3.0.0 went out. Thanks for reporting and making a PR so quickly
