### ISSUE TITLE
Quick question about firebase sdk support

### ISSUE THREAD

**Issue by darthzyklus** [prescottprue/react-redux-firebase#782]
Hello world,  before asking my question I want to say thanks for this amazing project. 

My question is about if this project supports firebase 7.2 sdk and since what version release is supporting this sdk?

**Comment by prescottprue** [comment]
No problem, glad to save time

Yes, 7.2.0 version of the SDK works with this project. I would suggest the using latest (by calling `npm i --save react-redux-firebase`), but it has also been run successfully with the older `v2.*.*` series.

That said, there are not currently redux actions + reducers for some of the new Firebase features, but that should not limit your usage of them since the new features (such as analytics) don't really benefit all that much from data going into redux (at least not that I have found yet).
