### ISSUE TITLE
Odd behavior when requesting all users (only when authenticated)

### ISSUE THREAD

**Issue by coloradocolby** [prescottprue/react-redux-firebase#784]
Let me first explain the desired effect:

An authenticated user navigates to `/users` in my application and is presented with all users. (for simplicity, let's assume no pagination) Once the call is finished, the authenticated should see all users loaded on the page.

The odd behavior that I'm experiencing is that when a user is authenticated and navigates to this route, their user card is loaded first, then each consecutive user is loaded. This all happens very fast but is undesirably jarring. Again, this **_only_** happens when a user is authenticated and **_only_** when I request all users from firestore. When I'm not authenticated and request all users, all users load at the same time. Here is a gif to demonstrate what's hapenning

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/21346716/67448159-cac40e00-f5db-11e9-997c-e59d5fc7333b.gif)

In the provided gif you can see another call made to get a list of numbers - all numbers load up at the same time.

I'm interested if anyone else has seen similar behavior or has any thoughts as to why this is happening.

Here is my config and a simplified version of my component:
```
const rrfProps = {
  firebase: firebase,
  config: {
    userProfile: 'users',
    useFirestoreForProfile: true, // use firestore for profile instead of Realtime DB
  },
  dispatch: store.dispatch,
  createFirestoreInstance, // <- needed since using firestore
}
```

```
const Users = () => {
  useFirestoreConnect('users')

  const users = useSelector(state => state.firestore.ordered.users)

  if (!users) return <p>Loading...</p>

  return (
    <main>
        {users.map((u, i) => (
          <div key={i}>
            <ListItem button>
              <ListItemText primary={u.displayName} />
            </ListItem>
          </div>
        ))}
    </main>
  )
}
```

**Comment by prescottprue** [comment]
Did you try passing an array to `useFirestoreConnect`? Like `useFirestoreConnect(['users'])` since it is supposed to be a list of listener settings

Not sure if it is setup to accept just a string directly - I'll check though

**Comment by coloradocolby** [comment]
Yeah I tried that, same result... Any other ideas as to what it might be?

**Comment by coloradocolby** [comment]
Actually, why would I be seeing `@@reduxFirestore/DOCUMENT_ADDED` dispatched multiple times each time this page loads? Since behind the scenes no documents were added to Firestore, I'm not sure why this action would be dispatched 🤔

**Comment by prescottprue** [comment]
@coloradocolby I agree, we should see that when documents are added, not on main list listener resposne - Which version of redux-firestore are you using, going to try to reproduce later today

**Comment by coloradocolby** [comment]
I’m on latest!

**Comment by prescottprue** [comment]
@coloradocolby Are you able to provide a codesandbox or similar to replicate the issue? I wasn't able to reproduce earlier, but maybe I missed something

**Comment by coloradocolby** [comment]
> @coloradocolby Are you able to provide a codesandbox or similar to replicate the issue? I wasn't able to reproduce earlier, but maybe I missed something

No problem @prescottprue. I added you as a collaborator on the project (just a pet project of mine). I'm guessing just check your inbox for that? To reproduce, you should just need to run the project, authenticate, and navigate to and from the 'riders' section of the app

**Comment by prescottprue** [comment]
I see it, I'll look into reproducing tomorrow

On initial glance, a few things I noticed (though they probably don't have to due with the issue):

* [This `storeAs` should be dynamic](https://github.com/coloradocolby/unehub/blob/14ac4d2c042752403979cf8eeab9102be4bab8a6/src/components/Profile.jsx#L49) - or else every profile that is loaded will replace the previous one. If you are loading a single item you probably want to use data (mentioned below)
* If you are [selecting just one item by id](https://github.com/coloradocolby/unehub/blob/14ac4d2c042752403979cf8eeab9102be4bab8a6/src/components/Profile.jsx#L53-L59), you should use `data`
* This should be an array of listeners - https://github.com/coloradocolby/unehub/blob/14ac4d2c042752403979cf8eeab9102be4bab8a6/src/components/Tricks.jsx#L28
* You can use `isLoaded` and `isEmpty` [here](https://github.com/coloradocolby/unehub/blob/14ac4d2c042752403979cf8eeab9102be4bab8a6/src/components/Riders.jsx#L28-L30) instead of checking for length, but either way works

**Comment by coloradocolby** [comment]
@prescottprue thanks for taking a look - I appreciate the feedback! Any luck with repro?

**Comment by prescottprue** [comment]
I was able to repro, didn't get to the change until today. It appeared to be due to an extra unnecessary listener - made [this PR with the change and pictures explaining](https://github.com/coloradocolby/unehub/pull/1).

Going to close since I don't believe there is an issue here, but feel free to ping me [over Gitter](https://gitter.im/redux-firebase/Lobby) if you would like more explanation.
