### ISSUE TITLE
bug(core): async/await code in profileFactory causes "regeneratorRuntime is not defined" error

### ISSUE THREAD

**Issue by hunterbecton** [prescottprue/react-redux-firebase#786]
**What is the current behavior?**

Getting `WebpackError: ReferenceError: regeneratorRuntime is not defined` on `react-redux-firebase` packages when I run `gatsby develop` or `gatsby build`.

I've tried installing and adding plugins like `@babel/plugin-transform-runtime` to a `.babelrc` file without any luck.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

Clone repo: https://github.com/hunterbecton/st-bug-1.git

Run `npm install`

Run `gatsby develop`

**What is the expected behavior?**

Successful develop and build without errors.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

Nothing has been updated or changed to my knowledge. I easily replicated the issue by moving all the config and setup files from my original project into a new gatsby project (reflected in the repo above.)

  System:
    OS: macOS 10.14.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.14.0 - /usr/local/bin/node
    npm: 6.12.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.70
    Firefox: 69.0.1
    Safari: 12.0.2

**Comment by prescottprue** [comment]
Thanks for reporting - I believe this is due to the [recent addition of async/await code in `v3.0.3`](https://github.com/prescottprue/react-redux-firebase/commit/aebe5cd154818228a125ab59addcd4b3b0fb2585#diff-1ea25756c9a60d368fabffd19b77c0feR290) (from [this PR for adding promise support for `profileFactory`](https://github.com/prescottprue/react-redux-firebase/pull/778) by @dannyvaughton). I'll look into removing that, but in the meantime you should be able to go back to v3.0.1 or v3.0.0.

Didn't realize this would be breaking or else it wouldn't have gone out in a patch. I'll update this issue with progress on the fix

**Comment by prescottprue** [comment]
@dannyvaughton I am going to start by removing promise support for the `profileFactory` in v3.0.4, then I'll add back that support in a later version in a way that is not breaking for this type of setup (most likely without `async/await`).

Thanks to all for reaching out

**Comment by dannyvaughton** [comment]
@prescottprue Sure, no worries. Sorry, I had no idea this was breaking either.

**Comment by prescottprue** [comment]
All good! I'm sure we will figure out a way to get it in there without a breaking change - just wanted to make sure you knew that the next patch release would break any promise logic you have in the `profileFactory`

**Comment by prescottprue** [comment]
Fixed in v3.0.4 - thanks for reaching out!
