### ISSUE TITLE
I.hasOwnProperty("process")

### ISSUE THREAD

**Issue by darioielardi** [prescottprue/react-redux-firebase#80]
just import reactReduxFirebase and firebaseStateReducer, set them and:
undefined is not a function (evaluating 'I.hasOwnProperty("process")')

**Comment by prescottprue** [comment]
Set them how? Can you provide a repository to reproduce the error? This is one I haven't seen.

How are you "setting them"? In what context?

**Comment by darioielardi** [comment]
1. I install the module, import firebaseStateReducer
2. I declare the firebaseStateReducer as firebase in the combineReducers function
3. I import firebaseConnect
4. The app on the android simulator crash ( red screen ) and the error appears

**Comment by prescottprue** [comment]
Tons of questions:
* Which simulator?
* Is this a `react-native` app?
* Are you using a starter/generator of some kind?
* Are you using webpack/babel or any other type of bundling/building tools?
* If using webpack, what version (i.e. v1 or v2)?

**Comment by darioielardi** [comment]
Sorry for not being​ precise in the first message and thanks for your
answer.
I'm developing on windows 10 a react native app, with the native starter
kit.
When I 'react-native run-android' ( packaged with the react-native packager
) either on the android studio simulator and on the device, the app crash
and that error appears.

Il mer 15 mar 2017, 19:00 Scott <notifications@github.com> ha scritto:

**Comment by prescottprue** [comment]
@darioielardi React-native is not yet supported fully by `react-redux-firebase`. We are working on react-native compatibility on the `react-native` branch.

No promises here, but feel free to checkout the [`react-native` branch](https://github.com/prescottprue/react-redux-firebase/tree/react-native) and [it's associated PR](https://github.com/prescottprue/react-redux-firebase/pull/81). You can even point to within your package file (since it include the dist folder in git tracking) using `git://github.com/prescottprue/react-redux-firebase.git#react-native`.

This functionality will make it back into master and a released version after it is all working correctly so keep an [eye on the pull request](https://github.com/prescottprue/react-redux-firebase/pull/81).

**Comment by darioielardi** [comment]
ok prescott, thanks for the availability.

**Comment by prescottprue** [comment]
@darioielardi Have you gotten a chance to try the `react-native` branch yet? I have begun work on `1.4.0` and would love it include the react-native stuff

**Comment by darioielardi** [comment]
I'd like to give it a try. When I'll do that I will let you know.

**Comment by prescottprue** [comment]
[`v1.4.0-alpha`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.4.0-alpha) includes the initial `react-native` capabilities. Note that it requires [a different setup than usual](https://github.com/prescottprue/react-redux-firebase/blob/v1.4.0/docs/recipes/react-native.md).

Authentication is not currently supported as it does not work through the Firebase JS library. The current plan is going to be to investigating integration of [react-native-firebase](https://github.com/invertase/react-native-firebase), which might change the setup a bit again.

**Comment by prescottprue** [comment]
[`v1.4.0-beta`](https://github.com/prescottprue/react-redux-firebase/releases/tag/v1.4.0-beta) has improved `react-native` capabilities and a [complete react-native example including auth](https://github.com/prescottprue/react-redux-firebase/tree/v1.4.0/examples/complete/react-native).

Authentication is now supported thanks to @kudorori (more details in #87).
