### ISSUE TITLE
fix(example): firestore example should work out of the box

### ISSUE THREAD

**Issue by harish-aka-shivi** [prescottprue/react-redux-firebase#819]
**Description**
Copying and running the Firestore example should work but it does not work. The user faces a lot of issues. As discussed in #791, it needs some fixing. @prescottprue has worked on it in his branch fix-firestore-examples, where he is moving this example to simple-firestore-example code but these errors have not been fixed yet

So, I think this can be made a separate issue just to fix the firebase example and then later it can be moved to the simple-firestore-example.

**Comment by prescottprue** [comment]
@harish-aka-shivi Thanks for reporting. As noted in #791 the firestore example has been updated - let me know if things aren't working as expected for you.

You may already know if it, but you may prefer using [generator-react-firebase](https://github.com/prescottprue/generator-react-firebase) for starting a new project instead of needing to copy the example anywhere. As you saw on that other branch, I was actually working on updating the example to use the output of that generator (also makes keeping things up to date much easier)
