### ISSUE TITLE
question(query): How to add multiple userProfile during redux binding for firebase?

### ISSUE THREAD

**Issue by SiddharthVarshney** [prescottprue/react-redux-firebase#825]
How can I add multiple or two collection name in my userProfile during redux binding for firebase?
Basically I have two different collections that collect user for registration and login purpose differently.
I have tried this to achieve this but the console is throwing error :

> Unhandled Rejection (FirebaseError): Missing or insufficient permissions.

```
{
        useFirestoreForProfile: true,
        userProfile: "paricipantData" || "caData",
        attachAuthIsReady: true
 }
```
Is there is any other possible way to achieve this?

**Comment by prescottprue** [comment]
There isn't a current way to achieve this through react-redux-firebase - you may want to start by creating a cloud function which copies data over and have the user just write to one collection. This is actually a pattern I have used in the case of needing to have public/private profiles (since the cloud function can strip any unwanted data as it is copying).

The error you are getting in the console is most likely due to rules blocking your from writing to `participantData` since the `|| 'caData'` (or case) will not be executed.

**Comment by prescottprue** [comment]
Going to close since supporting this is out of the scope of the library and can be handled using cloud functions as mentioned above. Thanks for reaching out!
