### ISSUE TITLE
bug(helpers): dataToJS retrieves a new copy each render

### ISSUE THREAD

**Issue by Venryx** [prescottprue/react-redux-firebase#84]
Using dataToJS() in the @connect() function breaks the shouldComponentUpdate functionality -- that is to say, every time @connect() calls dataToJS(), it gets a new object returned even if the database contents are the same.

This is an issue as it causes unnecessary re-rendering of the component.

Is this a known issue? Is there a workaround for it?

**Comment by prescottprue** [comment]
@Venryx This is something that seems to be due to the usage of immutable.

The plan for `v2.0.0` ([outlined in the roadmap](http://react-redux-firebase.com/docs/roadmap.html#upcoming-major-version-v200)) is to remove the usage of immutable, which would mean there will be no more need for `dataToJS` in the `connect`. Hopefully that will get `shouldComponentUpdate` to work correctly and not cause unnecessary re-rendering.

**Comment by Venryx** [comment]
Here's a (not that great) workaround, for the moment:
```
class DBPathInfo {
	lastTimestamp = -1;
	cachedData;
}
let pathInfos = {} as {[path: string]: DBPathInfo};
export function GetData(firebase: FirebaseDatabase, path: string) {
	let info = pathInfos[path] || (pathInfos[path] = new DBPathInfo());
	var timestamp = (firebase as any)._root ? (firebase as any)._root.entries.find(a=>a[0] == "timestamp")[1].get(path) : null;
	if (timestamp && timestamp != info.lastTimestamp) {
		info.lastTimestamp = timestamp;
		info.cachedData = helpers.dataToJS(firebase, path);
	}
	return info.cachedData;
}
```

As can be seen, it checks if the data at a position is new each time, based on the timestamp.

If so, it transforms that raw data using the dataToJS transformer, then returns it.

If not, it returns the cached result of that operation from last time.

The main concern atm is that I'm not sure it'll work for "embedded" data, ie, data that was retrieved from an ancestor node-request, and therefore has no "timestamp" property. I suppose in that case, I could have it search for ancestor timestamps as well, but that I'm not sure if the timestamps for node-requests at multiple depths are kept in-sync.

**Comment by Venryx** [comment]
@prescottprue Ah, sounds good. : )

Thankfully, the performance impact is not enough yet in my app to be a problem. Perhaps v2 will be ready by the time it is needed. (I'm pretty sure it would be a problem eventually)

**Comment by prescottprue** [comment]
[Roadmap](http://react-redux-firebase.com/docs/roadmap.html#upcoming-major-version-v200) updated

**Comment by Venryx** [comment]
The Roadmap says "Progress: v2.0.0-alpha has been started, view the branch", however the link gives "page not found".

Has work started on it, or was it just a placeholder for soon-to-be-done work?

And if work has started, how far is it? (if it's far enough, I might prefer to try/contribute-to it even if it's partially broken, as I'm currently doing an optimization phase in my project, and this is somewhat of a blocker for an optimization I have planned)

In the meantime, I'll see if there's a way I can "resolve" the ImmutableJS maps to normal objects manually. (perhaps in a middleware)

**Comment by Venryx** [comment]
I managed to update the library myself to use plain JS objects.

Granted, I implemented the change as a "hack" rather than an organic reworking, but for people just waiting for the next version, it seems to work fine.

The changes I made are as follows.

"node_modules/react-redux-firebase/dist/reducer.js":
```diff
-var initialState = (0, _immutable.fromJS)(emptyState);
+var initialState = emptyState;
+
+var u = require("updeep");
+initialState.getIn = function(pathNodes, notSetValue) {
+	let result = this;
+	for (let pathNode of pathNodes) {
+		if (result == null) break;
+		result = result[pathNode];
+	}
+	if (result == null)
+		return notSetValue;
+	return result;
+};
+initialState.setIn = function(pathNodes, value) {
+	return u.updateIn(pathNodes.join("."), value, this);
+};
+initialState.deleteIn = function(pathNodes) {
+	return u.updateIn(pathNodes.join("."), undefined, this);
+};
+
+_immutable.fromJS = a=>a;
```

I also had to run `npm install --save updeep` in my project, since the code above depends on that package for updating deep keys/data -- the repo for it is here: https://github.com/substantial/updeep

**Comment by prescottprue** [comment]
Nice @Venryx! Will check into this a bit more. I believe I was able to get something similar working without `updeep`, but this is great for comparison.

**Comment by prescottprue** [comment]
Would be interested to see if [v2.0.0-alpha.*](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.0.0-alpha.7) versions solve this for you since ImmutableJS is not used.

`v2.0.0-beta` is going to be out very soon, and should also solve it. If that is not the case, I would like to get to the bottom of it before bringing `v2.0.0` out of pre-release.

**Comment by prescottprue** [comment]
v2 has seen major adoption, so this thread may be dead, but those still working with v1:

>`dataToJS` does not need to be used in `connect`! Plenty go without it all together

Since data is stored in an Immutable Map in v1, you can just pass the Map object down as props in the connect function. That way JS object conversion (most often through `.toJS()` or `dataToJS`) can happen in other places such as Component methods and the `render` function.

This can be particularly useful if you want to use any of the [handy Immutable methods](https://facebook.github.io/immutable-js/docs/#/) within your code (which are removed when converting it to a JS object).

In the near future there will be a short section about this in the v1 docs. Closing since this can be worked around with v1, and was intentionally designed to not happen for v2.
