### ISSUE TITLE
Question: usage of initialState and history in configureStore

### ISSUE THREAD

**Issue by henricazottes** [prescottprue/react-redux-firebase#847]
Hi,

I'm not an expert in redux, I just have a question about the example [given here](https://github.com/prescottprue/react-redux-firebase/blob/master/examples/complete/typescript/src/store.ts) which shows how to configure the store using `configureStore`:

``` typescript
export default function configureStore(initialState?: any, history?: any) {
  const createStoreWithMiddleware = compose(
    typeof window === "object"
    && typeof (window as any).devToolsExtension !== "undefined"
    ? () => (window as any).__REDUX_DEVTOOLS_EXTENSION__
    : (f: any) => f,
  )(createStore);

  const store = createStoreWithMiddleware(rootReducer);

  if ((module as any).hot) {
    // Enable Webpack hot module replacement for reducers
    (module as any).hot.accept("./reducer", () => {
      const nextRootReducer = require("./reducer.js");
      store.replaceReducer(nextRootReducer);
    });
  }

  return store;
}
```
Why aren't `initialState` and `history` arguments used?

**Comment by prescottprue** [comment]
Initial state can be assed into your redux store as the second argument to createStore ([as seen in the redux docs](https://redux.js.org/recipes/configuring-your-store/#the-solution-configurestore)) - history is not used anymore since browserHistory is most commonly used directly now [as noted in the react-router docs](https://reacttraining.com/react-router/web/api/history)
