### ISSUE TITLE
feat(firebase): database updates when offline

### ISSUE THREAD

**Issue by manishtpatel** [prescottprue/react-redux-firebase#99]
I am working on react-native, ios, firebase, redux-react app. App changes data directly into firebase, then root component listen for 'on' for pretty much all data and any changes are reflected into redux store using 'on' event. Works pretty well but can't handle disconnected mode as data does change but 'on' doesn't fire. 

Ideally I would like to fire 'on' event when data changes even in the disconnected mode.

Thats how I found this project, but after reading through documents i didn't see any mention of how disconnected mode is handled, can someone shed some light on what is expected in disconnected mode?

**Comment by prescottprue** [comment]
@manishtpatel This is not currently supported. react-native support is in its early phases (only 1.4.0-* pre-release versions)

If you persist the redux store, your data will still be there, but changes to queries will not fire `.on` event listeners.

The plan for `v2.0.0` is to actually update the store directly (so you wouldn't have to depend on listeners updating), but it is difficult to do since when data changes, it must be confirmed that user has rights to make those changes.

**Comment by prescottprue** [comment]
#253 may be releated

**Comment by prescottprue** [comment]
@manishtpatel Offline database updates are supported if you use [the native-modules integration with `react-native-firebase`](http://docs.react-redux-firebase.com/history/v2.0.0/docs/recipes/react-native.html#native-modules). There is also [the react-native-firebase complete app example](https://github.com/prescottprue/react-redux-firebase/tree/v2.0.0/examples/complete/react-native-firebase) which shows how to use this integration.

**Note**: It requires using v2, which is available on the `canary` tag (i.e. `npm i --save react-redux-firebase@canary`).

Since support through Firebase's native modules is the only real way to effectively support offline, going to close.
